### ISSUE TITLE
OrderNo/date mix-up?

### ISSUE THREAD

**Issue by chkania** [Michael-Beutling/Amazon-MoneyMoney#1]
Hi Michael!

Thanks for taking the effort to write this nice extension!
Unfortunately the current version is not working for me. After a while the data import stops with an error "amazon-orders.lua:291:" After the colon it shows an amazon order no. If I look for this number in my order history there is no match.
As the moneymoney protocol is empty I am note able to provide more details.
Would be very happy if you could fix this issue.
How can I provide further details?

Cheers
Christoph

**Comment by Michael-Beutling** [comment]
Hi Christoph,

this is strange, normally is the text after the colon is order date.
Do You have the App-Store version or the version from the homepage of MoneyMoney?

regards Micha

**Comment by chkania** [comment]
Hi Micha,

I have downloaded it from the website.

Christoph

**Comment by Michael-Beutling** [comment]
okay, do you dare to make a backup from the MoneyMoney database and install the beta version of MoneyMoney to turn on the plugin debug messages?

Micha

**Comment by chkania** [comment]
Beta version is running now. How to enable debug mode?

**Comment by chkania** [comment]
Debug Output
https://gist.github.com/chkania/e6992c37692f5b6a43a5f772616c8af8

**Comment by Michael-Beutling** [comment]
thank you for the snippet, I see the problem and can fix it.

**Comment by Michael-Beutling** [comment]
give them a try: [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue1/amazon-orders.lua)

**Comment by chkania** [comment]
Sorry, now we have a different error: https://gist.github.com/chkania/530ffc2853dd5ffc98d887281d31ddce

**Comment by Michael-Beutling** [comment]
next shot: [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue1/amazon-orders.lua)

**Comment by chkania** [comment]
This is working now!
Thanks a lot!
