### ISSUE TITLE
Error: Invalid order found, a account reload can be fix it.

### ISSUE THREAD

**Issue by MirkoDziadzka** [Michael-Beutling/Amazon-MoneyMoney#11]
Wenn ich das Plugin über meinen Amazon account laufen lasse, dann bekomme ich die error Meldung `Error: Invalid order found, a account reload can be fix it.` nach 1900 bzw 2490 importierten Transaktionen. Die letzte geladene Transaktion is bei mir vom 16.1.2003

Ein reload hilft nicht. 

- Was kann ich tun, um das Problem zu debuggen?
- Was kann ich tun, um die Fehlerhafte Transaktion zu ignorieren und ältere Transaktionen zu laden.

Auf der Amazon Webseite gibt es für dieses Jahr noch genau eine weitere Transaktion, die auf einer weiteren Page steht. Diese sieht erstmal normal aus.

**Comment by Stopuhr** [comment]
Ich hatte den selben Fehler, mit dem aktuellen Release war er weg. Also noch einmal testen!

**Comment by Michael-Beutling** [comment]
Die Meldung `Error: Invalid order found, a account reload can be fix it.` in MoneyMoney löschen. Das Plugin kann im Nachgang keine Umsätze entfernen.

Wenn es noch nicht geladene Bestellungen gibt, dann bitte prüfen ob es Bestelldetails gibt.

**Comment by mirkodziadzka-avi** [comment]
@Michael-Beutling Danke für den Tip. Ich habe jetzt nochmal zwei Dinge probiert:

Amazon Konto in MoneyMoney gelöscht und neu angelegt. Einmal mit version 1.07 und einmal mit 1.08

1. version 1.07 - selber Effekt wie bisher, allerdings kommt es(nach mehrfachem reload) diese mal nur bis ins Jahr 2006 statt bis 2003. 
1. version 1.08 - es dauert eine Weile (unten links sehe ich das er alle Jahre abgeht) aber am Ende sind **keine** Transaktionen in MoneyMoney

Ich nutze die MoneyMoney Beta Version 2.3.25 (354) wegen PSD2 interface

**Comment by Michael-Beutling** [comment]
@MirkoDziadzka Du hast nicht zufällig ein Geschäftskonto? Nachdem alle Jahre durchgelaufen sind, hätte das Plugin noch die Detailansichten der Bestellungen abrufen müssen.

**Comment by mirkodziadzka-avi** [comment]
@Michael-Beutling Nein, personal. 
Kann ich irgendwie einfach ein debug log anschalten? Ich habe mir den source noch nicht angeschaut.

**Comment by Stopuhr** [comment]
Einige Verzeichnisse weiter oben und dann wieder eines runter ;-) Suche nach Amazon-orders.json, in der kannst du ein debug einstellen. 
Macht ggf aber das Protokoll voll und träge.

**Comment by Michael-Beutling** [comment]
@MirkoDziadzka Im Log von MoneyMoney kann man die Statusmeldung sehen. 
Nach dem die Übersichten (Jahre) eingelesen wurden, wird das Message Center abgerufen, anschließend werden die Detailansichten zu den Bestellungen abgefragt.
Das Debugging findet mehr mit dem Browser statt, im Script sind Xpath Anfragen die man mit einen Browser prüfen kann. 
z.B. [Bestellung in Übersicht](https://github.com/Michael-Beutling/Amazon-MoneyMoney/blob/9bcd6caf6a26ddabaeae7713629bc11e2c7e077d/amazon-orders.lua#L754)
ergibt für den Browser:
`$x('//div[@id="ordersContainer"]//div[@class="a-box-group a-spacing-base order"]')`
Der Ausdruck liefert ein Array von Elementen in den jeweils eine Bestellung drin sein sollte.
Wenn man sich nicht sicher ist wo das Script genau hinkommt oder welchen Wert gerade eine Variable hat, muss man altmodisch print() Befehle einstreuen. (Feature-Request: Ein echten Debugger für MoneyMoney Plugins ;) )

**Comment by MirkoDziadzka** [comment]
@Michael-Beutling Danke, Ich werde dem am Wochenende mal nachgehen

**Comment by Michael-Beutling** [comment]
@MirkoDziadzka Nebenan ist ein ähnliches Problem, evtl. hilft der Lösungsansatz
https://github.com/Michael-Beutling/Amazon-MoneyMoney/issues/9#issuecomment-615796267

**Comment by MirkoDziadzka** [comment]
@Michael-Beutling Danke, ich habe mir das heute mal im Detail angesehen. Also nochmal MoneyMoney aktualisiert (aktuellste Beta) und die 1.08 version vom Amazon Plugin. Jetzt lädt er bis Juli 2002, alle Transaktionen bis dahin sind auch da.
Das problem von https://github.com/Michael-Beutling/Amazon-MoneyMoney/issues/11#issuecomment-613903761 (keine Daten) sehe ich nicht mehr.

 Für ältere Transaktionen (vor Juli 2002) hat Amazon anscheinend auch grade keine Detaildaten mehr 

> Bestellung kann nicht gefunden werden

Da kann das Plugin auch nicht viel machen. Also für mich funktioniert es jetzt soweit, wenn Amazon wieder die alten  Daten hat werde ich mal den Cache für die Jahre davor mal manuell löschen und es weiter probieren.

Danke für die Hilfe.
