### ISSUE TITLE
Für mich funktioniert das leider noch nicht. Bei mir wird nur eine Bestellung korrekt in MoneyMoney importiert. Alle anderen werfen Fehler im Log a la:

### ISSUE THREAD

**Issue by Michael-Beutling** [Michael-Beutling/Amazon-MoneyMoney#14]
Für mich funktioniert das leider noch nicht. Bei mir wird nur eine Bestellung korrekt in MoneyMoney importiert. Alle anderen werfen Fehler im Log a la:

`          1> string='unkown elements' string='13. Februar 2019#Tim Pritlove#EUR 14,95#Ersatzteil Kopfhörer#304-5405586-5482757'
`

_Originally posted by @timpritlove in https://github.com/Michael-Beutling/Amazon-MoneyMoney/issues/9#issuecomment-616833805_

**Comment by Michael-Beutling** [comment]
Zahlendreher :(
Jetzt geht es in der Beta weiter:
https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/beta/amazon-orders.lua

EDIT: 'tschuldigung das Rumgespiele mit Github... aber an Irgendjemand muss man es ja mal ausprobieren...

**Comment by timpritlove** [comment]
Jetzt läuft's!

**Comment by Michael-Beutling** [comment]
Danke für die Rückmeldung.

**Comment by timpritlove** [comment]
Danke fürs Fixen und Programmieren. Wann wird das als Release rausgehen?

**Comment by Michael-Beutling** [comment]
Herr Haller hat schnell geliefert :)

https://github.com/Michael-Beutling/Amazon-MoneyMoney/releases/tag/V1.09
