### ISSUE TITLE
Intervall Mix

### ISSUE THREAD

**Issue by thymde** [Michael-Beutling/Amazon-MoneyMoney#15]
Moin,
Erst einmal vielen Dank für das Plugin. Super!

Eine tolle Erweiterung fände ich, das Ausgleichsintervall nicht direkt pro Objekt, sondern als Summe z.B. für jedes Monatsende zu rechnen. Dann hätte man im Balkendiagramm eine praktische Übersicht darüber wie viel man in einem Zeitraum ausgegeben hat.

Beste Grüße,
Tim

**Comment by Michael-Beutling** [comment]
Meinst Du so: 
https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/monthly/amazon-orders.lua

**Comment by Michael-Beutling** [comment]
Das konnte ich jetzt nicht nachvollziehen.  
Sollverhalten: Wenn man mit CMD+R alle Konten aktualisiert wird  einmal der Account ausgelesen und alle Kontenübersichten aktualisiert. 
Mit Shift+CMD+R wird für das jeweilige Konto der Account immer ausgelesen und nur die eine Kontoübersicht aktualisiert.

Welches Verhalten hast Du?

**Comment by thymde** [comment]
Sorry, das wahr wohl ein vorschneller Fehlalarm. Ich hatte das Konto gelöscht und neu angelegt - irgendwie sah es so aus als würde beim zweiten aktualisieren für jede Ansicht das Konto ausgelesen werden. Ich kann es aber jetzt auch nicht mehr nachvollziehen...funktioniert wie gedacht.
