### ISSUE TITLE
Rücksetzung Amazon Zugang

### ISSUE THREAD

**Issue by iberberich** [Michael-Beutling/Amazon-MoneyMoney#16]
Übermorgen,
Vielen Dank für das sehr schöne Plug-in.
Hatte meine Amazoneinkäufe über "amazon-orders.lua“ erfolgreich heruntergeladen. Alles einwandfrei. Leider habe ich das Kto „aus Versehen“ gelöscht. Jetzt lassen sich in einem „neuen“ Kto die alten Daten von Amazon leider nicht  mehr laden; Moneymoney hat sich gemerkt, dass diese Daten schon einmal abgefragt wurden (?). Kann ich die Abfrage wieder zurücksetzen?

Herzliche Dank
Ingolf Berberich

**Comment by iberberich** [comment]
Sorry, die obere Anrede sollte natürlich Herr Beutling sein.

**Comment by Michael-Beutling** [comment]
Hallo Ingolf (Ich gehe mal davon aus das ich der ältere bin :),

im Master ist eine Version bei der man die Caches zurücksetzen kann.
In den Kontoeinstellungen bei Notizen das Attribut resetCache auf irgendeinen Wert setzen, siehe Screenshot.
Ich gebe den Stand an Herr Haller zum signieren, da Du vermutlich keine Betaversion von MoneyMoney hast, mit der das Plugin lauffähig wäre.

Gruß Micha

![Bildschirmfoto 2020-07-14 um 14 12 53](https://user-images.githubusercontent.com/2708948/87424886-12148380-c5dd-11ea-8f16-37056704b978.png)

**Comment by iberberich** [comment]
Hallo Micha,

Mit dem Alter bin ich mir nicht sicher; bin immerhin 62.
Danke dir für die Hilfe.

Herzliche Grüße
Ingolf

**Comment by Michael-Beutling** [comment]
Hallo Ingolf,

okay, die Anzeige auf meinen Betriebsstundenzähler zeigt eine kleinere Zahl... Du hast gewonnen.

Die signierte Version ist da: 
https://github.com/Michael-Beutling/Amazon-MoneyMoney/releases/tag/V1.10 
oder 
https://moneymoney-app.com/extensions/amazon-orders.lua

Hoffe es hilft. 

Gruß 
Micha
