### ISSUE TITLE
What are the differences between the different Amazon accounts

### ISSUE THREAD

**Issue by luxio** [Michael-Beutling/Amazon-MoneyMoney#17]
Hi,

thank you for the great extension.

After entering my amazon login credentials I can chose from different accounts (mix, normal, inverse, monthly, yearly).

![Monosnap 2020-07-25 13-00-22](https://user-images.githubusercontent.com/1497217/88455651-4dce0980-ce77-11ea-98e7-6e9eaf60d825.png)

What are the differences between these accounts?

Best,

Stéphane

**Comment by Michael-Beutling** [comment]
Hi Stéphane,

normal = purchases as minus value, refunds and bonus as plus value
inverse = normal * -1, when you use the normal and inverse account you have as sum = 0 for the book holding, but separates accounts

mix = normal and inverse as one account, the sum is always zero

months and yearly = like mix but the counter booking is done monthly/yearly

You can active all accounts together and show which kind of account(s) better fit to your accounting. You can safe delete the unused accounts.

greets Micha

**Comment by luxio** [comment]
@Michael-Beutling thanks for clarification.
