### ISSUE TITLE
Zwei-Faktor Authentifizierung

### ISSUE THREAD

**Issue by bmikaili** [Michael-Beutling/Amazon-MoneyMoney#19]
Hey, seitdem ich die Zweifaktor Authentifizierung drin habe, geht es nicht mehr. Klappt das nicht damit?

**Comment by Michael-Beutling** [comment]
Unterstützt werden Captcha, OTP und Passcode. Ich habe auch 2FA aktiviert.
Ändere mal bitte das Passwort für den Amazon-Account in MoneyMoney, das erzwingt ein Login Fehler und ein löschen der Cookies.
Danach sollte es mit den richtigen Passwort klappen.

Gruß Micha

**Comment by bmikaili** [comment]
Hmm, habe es einmal falsch eingegeben, dann neu richtig. Auch Cache resetted, aber sehe immer noch keine Buchungen. In den Logs kommt aufs `GET` nur eine leere Response.

**Comment by Michael-Beutling** [comment]
Die Response ist nicht leer, da sind nur sehr viele Leerzeichen am Anfang und das Log macht keinen Zeilenumbruch.

Du kannst Dir die Antworten ansehen mit Cursor am Anfang setzen, Umschalttaste gedrückt halten und Cursor-Taste Runter drücken. Die Zeile sollte sich einfärben und mit cmd+v ist sie in der Zwischenablage.
Im Terminal:
`pbpaste >$TMPDIR/test.html;open $TMPDIR/test.html`

Dann sollte der Browser die Antwort anzeigen. 

Erfolgt in MoneyMoney keine 2FA Abfrage? 
Was für Amazon Account hast Du? Privat/Business 
Welche Meldungen kommen vom Script? Blaue Zeilen im Log-Fenster, bitte **nicht** das Log posten, da ist mehr drin als Du preisgeben möchtest ;)
Wenn Du 2FA wieder abschaltest funktioniert die Kontoabfrage?
Welche Version von MoneyMoney hast Du? (Apple Appstore/Von der Website/Beta)

Du könntest mit den oben beschriebene Vorgehen Dir die Etappen des Login-Prozesses ansehen. Evtl. kommen da Meldungen die ich nicht abfange.

**Comment by bmikaili** [comment]
Komisch, im Log steht: 

```bash
 5> Lade Kontostand und Umsätze für Amazon Orders ...
          5> Getting transactions since 01.08.2019...
          4> Received 100 transactions, 0 are new.
          5> Refresh monthly
```

Auch HTML kommt an.
Logs sind :
`Get order overview for "past six months"`
`Get page 1 from Amazon message center.`
`Get page 2 from Amazon message center.`
```
5> 1 orders from messages
5> 0
5> Logout
```

Zuletzt:
` 5> Received 0 transactions.`

Es erfolgt eine 2FA Abfrage, scheint auch zu klappen. Der Login scheint auch zu funktionieren. Ich nutze die Version von der Website. Ich habe einen Privaten Amazon Account.

**Comment by Michael-Beutling** [comment]
Das sieht gut aus, das Plugin ist eingeloggt. Es wird eine Bestellung im Message-Center gefunden. 2FA klappt also...wisch Schweiß von der Stirn...

Kommen keine Zeilen ala `  1> x/y Get details for order 123-1234567-1234567`?

Den Cache hattest Du mit resetCache gelöscht? Kam auch die entsprechende Meldung als vorläufige Buchung?

Tipp fürs Debuggen: Mit Shift+Cmd+R wird nur das selektierte Konto aktualisiert, dann ist das Log etwas aufgeräumter.

**Comment by bmikaili** [comment]
>Kommen keine Zeilen ala 1> x/y Get details for order 123-1234567-1234567?

Da kommt tatsächlich nichts in die Richtung.
Cache hatte ich gelöscht, da kam auch die Meldung.

**Comment by Michael-Beutling** [comment]
Hat etwas länger gedauert, aber ich glaube ich habe das Problem gefunden. Du hast Dein Amazon Konto auf Englisch, richtig?
Im master Branch ist eine unsignierte Version die das beherrscht, allerdings läuft die nur auf der Beta-Version. 
Ich habe diese Version zum signieren gegeben, dann ist die auch für Dich nutzbar.
Ich melde mich, wenn die signierte Version da ist.

**Comment by bmikaili** [comment]
Ah sehr cool! Danke dir fürs reinschauen! Meine logs waren leider nicht so hilfreich, wie bist du drauf gekommen, dass es die Sprache ist? Würd mich interessieren :D Gibt's nen Pull Request / Commit dazu?

**Comment by Michael-Beutling** [comment]
Das mit der Sprache war Zufall. Bei mir fehlten plötzlich die letzten Einkäufe. Amazon hat den Filter für die Bestellungen der letzten 6 Monate gegen 3 Monate ausgetauscht und das war hart im Source bei mir. Nachdem ich das gefixt hatte, dachte ich das ist evtl. auch ein Teil des Problems bei Dir. Dann fiel mir erstmalig auf, dass die Meldung des 6 Monate Filters bei Dir auf englisch ist.
So gesehen war Dein Log hilfreich, ich war nur zu doof es zu lesen und zu verstehen...

**Comment by Michael-Beutling** [comment]
So signierte Version ist jetzt auch da. https://github.com/Michael-Beutling/Amazon-MoneyMoney/releases/tag/V1.11

**Comment by bmikaili** [comment]
Danke für den fix!
