### ISSUE TITLE
Fehler bei sehr alten Bestellungen

### ISSUE THREAD

**Issue by bwess** [Michael-Beutling/Amazon-MoneyMoney#2]
Das Plugin funktioniert super und zeigt bei mir ca. 1200 Umsätze an.

Es zeigt aber persistent einen Fehler mit einer ungültigen Bestellung aus dem Jahr 2000 an, wahrscheinlich weil Amazon selber keine Details mehr dazu anzeigen kann.

Meine Bestellungen aus dem Jahr 1999 werden weder als Umsatz noch als Fehler angezeigt, anscheinend bleibt die Abfrage nach dem ersten Fehler stehen.

2001 und 2002 habe ich nichts bestellt, die erste funktionierende Umsatz ist von 2003.

Das Plugin sollte diese Fehler für sehr alte Umsätze m.E. ignorieren.

Ich kenne mich mit Lua (noch) nicht so aus, wenn ich es selber zufriedenstellend gelöst bekomme schicke ich ein pull request.

Fehlermeldung Plugin:
![Fehlermeldung Plugin](https://user-images.githubusercontent.com/22932951/78020493-d9181200-7351-11ea-9494-3f08f65e59b0.png)

Bestellansicht: ;)
![Bestellansicht](https://user-images.githubusercontent.com/22932951/78020501-dfa68980-7351-11ea-94d0-847600e6c929.png)

Fehlermeldung Amazon:
![Fehlermeldung Amazon](https://user-images.githubusercontent.com/22932951/78020512-e46b3d80-7351-11ea-8a65-b9a93bfcdf6a.png)

**Comment by Michael-Beutling** [comment]
Hallo,

die Bestellungen vor dieser Bestellung sind in Amazon wieder abrufbar?

Gruß Micha

**Comment by chkania** [comment]
Hi,

nein. Zumindest werden keinerlei Aufträge angezeigt. Es dauert aber 
„eine ganze Weile“, bis die Meldung kommt.

Grüße
Christoph
![](cid:65673C4C-49A8-42ED-98E6-0EAA70861A3A@gmx.de "PastedImage.png")

**Comment by bwess** [comment]
Hallo Micha,

> die Bestellungen vor dieser Bestellung sind in Amazon wieder abrufbar?

nein, die Bestellungen von 1999 sind bei Amazon auch sichtbar, aber die Details genausowenig abrufbar.

Ich habe es nicht überprüft, ob die danach 100% vollständig sind, aber gefühlt ist alles ab 2003 abrufbar.

Gruß Boris

**Comment by Michael-Beutling** [comment]
Versuche mal bitte [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue2/amazon-orders.lua)

Das sollte die alten Bestellung wo keine Details abrufbar sind entsprechend behandeln.

**Comment by chkania** [comment]
Hm, welchen Unterschied sollte ich sehen?
Ich sehe zahlreiche „skip order, get wrong number of elements“ und 
„can’t parse order details“ und „found invalid position“.

![](cid:D5DF6728-3133-4A55-ADDA-E106DB2F7CD6@gmx.de "PastedImage.png")


Außerdem habe ich jetzt eine Menge Aufträge so gespeichert, als wären 
sie vom heutigen Datum (s. Screenshot).
Dabei handelt es sich aber, soweit ich das sehe, tatsächlich um 
Aufträge, die vorher nicht importiert wurden.
Zu diesen Aufträgen (stichprobenhaft geprüft) finde ich in der 
Bestellhistorie einen „Auftragskopf“ aber keine Positionen. Versuche 
ich die Bestelldetails aufzurufen, kommt die Fehlermeldung „Bestellung 
kann nicht gefunden werden“

![](cid:2CE8F202-529F-40B7-AB4A-ABC5D280ABA6@gmx.de "PastedImage.png")

Die Frage ist, ob man Bestellungen, zu denen kein Datum und auch kein 
Betrag abgerufen werden kann, importieren möchte. Für mich persönlich 
ist diese Information wertlos und ich würde daher diese Aufträge nicht 
sehen wollen.

**Comment by bwess** [comment]
> Versuche mal bitte [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue2/amazon-orders.lua)
> 
> Das sollte die alten Bestellung wo keine Details abrufbar sind entsprechend behandeln.

Die drei Bestellungen von 1999 erscheinen jetzt zusammen mit der von 2000, erst als Warnung, danach als Fehler. Soweit so gut. Leider stehen sie ganz oben mit dem heutigen Datum:

![Error](https://user-images.githubusercontent.com/22932951/78077022-e06a0a80-73a7-11ea-9d68-e2bbe8fd475a.png)

Auf Amazon ist das Datum der Bestellungen sichtbar.
Das Datum der restlichen Bestellungen stimmt.

Es wurden 74 neue Umsätze gefunden, die bisher trotz vielfachen Abfragen nicht gefunden wurden. Aus dem Webinterface zusammengerechnet müssten es 466 Bestellungen sein, das Stichwort "Amazon contra" kommt 456 Mal vor, mit den 4 Fehlern fehlen noch 6 Bestellungen. Was könnte ich tun, um herauszufinden, an was das liegen könnte?

**Comment by Michael-Beutling** [comment]
Neue Version: [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue2/amazon-orders.lua)
 
Die Umsätze, die die fehlerhaften Bestellungen in MoneyMoney dokumentieren werden jetzt nur zweimal reportet, dann kann man sie löschen.  Das sie oben ohne das echte Datum einsortiert werden ist Absicht, damit man sie sofort bemerkt.

Das mit den fehlende Bestellungen konnte ich bei mir klären und zwar werden für 0 € Bestellungen (Retouren z.B.) keine Konterbuchungen angelegt.
 Finden kann man die mit MoneyMoney mit einen benutzerdefinierten Filter auf den Betrag von -0,01 bis 0,01 €.

Bitte prüfen ob das bei Dir auch der Fall ist.

**Comment by tobsen** [comment]
Die Version geht bei mir nicht:

`11:54:25  Ignoring 'amazon-orders.lua' because signature verification failed.`

Ich wollte sie probieren, da ich folgenden Fehler bei mir habe:

`amazon-orders.lua:291: 028-4406393-4636518`

Die Bestellnummer findet die Suche bei mir nicht im Konto. (Ggf. ist das aber ein neues Issue.)

**Comment by bwess** [comment]
> Die Umsätze, die die fehlerhaften Bestellungen in MoneyMoney dokumentieren werden jetzt nur zweimal reportet, dann kann man sie löschen. Das sie oben ohne das echte Datum einsortiert werden ist Absicht, damit man sie sofort bemerkt.

Ok, ist sinnvoll. Die Umsätze sind nach dem Löschen nicht wieder aufgetaucht. Sieht gut aus.
 
> Das mit den fehlende Bestellungen konnte ich bei mir klären und zwar werden für 0 € Bestellungen (Retouren z.B.) keine Konterbuchungen angelegt.
> Finden kann man die mit MoneyMoney mit einen benutzerdefinierten Filter auf den Betrag von -0,01 bis 0,01 €.
> 
> Bitte prüfen ob das bei Dir auch der Fall ist.

Leider nicht, bei mir erscheint nur eine Konterbuchung über 0€ für einen Artikel, den ich mit einem Gutschein gekauft habe (es gibt wie erwartet einen Differenzeintrag über den Kaufpreis).

Ich habe mal nach einer Retoure gesucht, die erscheint als negativer Betrag mit einer entsprechenden Konterbuchung.

**Comment by bwess** [comment]
Hallo Tobias,

> Die Version geht bei mir nicht:
> 
> `11:54:25 Ignoring 'amazon-orders.lua' because signature verification failed.`

um unsignierte Plugins testen zu können musst Du in den MoneyMoney Einstellungen die Optionen "An Beta-Tests teilnehmen und Vorabversionen anzeigen" aktivieren und "Digitale Signatur von Extensions überprüfen" deaktivieren.

**Comment by bwess** [comment]
> Ich habe mal nach einer Retoure gesucht, die erscheint als negativer Betrag mit einer entsprechenden Konterbuchung.

Ich habe noch eine zweite rausgesucht, die wird falsch erkannt: In der Bestellung sind zwei Artikel, einer davon wurde zurückgeschickt, in den Umsätzen erscheinen beide negativ mit einer positiven Konterbuchung. Das sieht auf der Amazon Webseite aber auch irreführend aus, dass nur einer erstattet wurde.

**Comment by Michael-Beutling** [comment]
> Ich habe mal nach einer Retoure gesucht, die erscheint als negativer Betrag mit einer entsprechenden Konterbuchung.
Okay, das ist das gewünschte Verhalten. Die Ware ging zurück und Du hast Geld zurückerstattet bekommen. Unterm Strich 0.
Ich hatte mich bei der Retoure ungenau ausgedrückt, korrekt war eine Retoure wegen Gewährleistung. Also Neuanlieferung ohne Rechnungsstellung, also 0 Betrag. 

> Ich habe noch eine zweite rausgesucht, die wird falsch erkannt: In der Bestellung sind zwei Artikel, einer davon wurde zurückgeschickt, in den Umsätzen erscheinen beide negativ mit einer positiven Konterbuchung. Das sieht auf der Amazon Webseite aber auch irreführend aus, dass nur einer erstattet wurde.
Hab ich mal neuen Fehler aufgemacht.
Zu den fehlenden Bestellungen auch.

**Comment by bwess** [comment]
Alles klar, ich betrachte dieses Issue mit der Version von oben als erledigt, danke Dir.

Ich weiß nicht, wie relevant die Fixes seit dem letzten Release sind, evtl. magst Du da dieses Plugin in der letzten Freakshow erwähnt wurde (https://freakshow.fm/fs248-public-static-final) ein neues Release machen...

**Comment by Michael-Beutling** [comment]
Das mache ich, allerdings würde ich gern noch den Bug #5 geklärt/gefixt haben.
