### ISSUE TITLE
amazon-orders.lua:508:    "bleibt bei alter Bestellung aus 2012 hängen"

### ISSUE THREAD

**Issue by WaramBuffett** [Michael-Beutling/Amazon-MoneyMoney#20]
**Zuerstmal vielen Dank für das sehr hilfreiche und gut gepflegte Plugin!**
Hier mein Issue:
Ich hatte das amazon Konto gelöscht, da auch bei mir keine neuen Bestellungen mehr geladen wurden. 

Leider kann ich seither keine vollständige Kontoaktualisierung mehr durchführen, es bleibt immer bei einer uralten Bestellung aus 2012 hängen:
<img width="434" alt="Bildschirmfoto 2020-08-18 um 18 39 09" src="https://user-images.githubusercontent.com/54305258/90540885-228ebf80-e182-11ea-9bf5-22f8760343a9.png">
So sieht sie aus:
<img width="924" alt="Bildschirmfoto 2020-08-18 um 18 35 35" src="https://user-images.githubusercontent.com/54305258/90541614-34bd2d80-e183-11ea-827f-4259cabb1387.png">

Ich brauche die alten Daten eigentlich nicht, kann sie aber afaik nicht ausschliessen? 
Cache habe ich resetet, alle 3 Versionen versucht.

Vielen Dank schon mal für's Prüfen.

**Comment by Michael-Beutling** [comment]
Hi,

Sind in der Bestellung irgendwelche Rückläufer oder Erstattungen?

Zum "Fixen" erstmal mit der alten Version die Bestellungen einlesen https://github.com/Michael-Beutling/Amazon-MoneyMoney/releases/tag/V1.10 ,nach dem vollständigen Einlesen auf die neue Version wechseln.

Interessant wäre ob die besagt Bestellung vollständig in MoneyMoney ist, also mit alle Positionen, Rückläufer usw.

Gruß Micha

**Comment by WaramBuffett** [comment]
Danke für den schnellen Support. Alle Buchungen scheinen wieder geladen zu sein.

Ja, die Bestellung hatte 2 Rücksendungen und somit 2 Erstattungen. In MoneyMoney wurde sie wie folgt eingelesen:
<img width="867" alt="Bildschirmfoto 2020-08-18 um 22 44 37" src="https://user-images.githubusercontent.com/54305258/90563662-83c78a80-e1a4-11ea-95ab-53d690adcd33.png">

**Comment by jzdm** [comment]
Hallo,
ich habe genau das gleiche Problem. Auch eine Bestellung aus 2012 mit drei Artikeln, zwei davon zurückgeschickt.
![CleanShot 2020-08-25 at 19 44 54@2x](https://user-images.githubusercontent.com/2634254/91209177-9ba28f80-e70b-11ea-860e-c31cea371fe6.png)
Nutze das Plugin erstmalig, daher gibt es noch keine importierte Historie, mit jedem neuen Versuch das "Konto" zu aktualisieren, verbleiben aber immer weniger zu ladende Positionen. Sind 111, waren anfangs > 450.

Probiere nun auch erstmal die empfohlene alte Pluginversion.

**Comment by jzdm** [comment]
Der Workaround funktioniert hier auch. Danke. Eine Rückkehr auf die aktuelle Version ist nach erfolgtem Import anscheinend problemlos möglich.

**Comment by Michael-Beutling** [comment]
Hallo,

hab im master die besagte Zeile auskommentiert und die Version zum signieren gegeben. 
Die Zeile ist ein Denkfehler von mir, das Problem was ich da lösen wollte muss ich anderes angehen, Sorry.
Ich melde mich wenn die signierte Version da ist.

Gruß Micha

**Comment by Michael-Beutling** [comment]
Die signierte Version ist da:
https://github.com/Michael-Beutling/Amazon-MoneyMoney/releases/tag/V1.12
oder
https://moneymoney-app.com/extensions/amazon-orders.lua

Gruß Micha
