### ISSUE TITLE
zwei Amazon Konten

### ISSUE THREAD

**Issue by Michael-Beutling** [Michael-Beutling/Amazon-MoneyMoney#23]
Ich habe das Plugin erst entdeckt und habe den ersten Abruf auf zwei verschiedene Amzn Konten hinbekommen. Ca. 250 und 340 Transaktionen.
Sobald ich aber die Konten aktualisieren möchte, bekommen ich auch eine Aufforderung, das Passwort neu einzugeben. Das alte wäre ungültig.

_Originally posted by @fazzer4x in https://github.com/Michael-Beutling/Amazon-MoneyMoney/issues/22#issuecomment-720157958_

**Comment by Michael-Beutling** [comment]
Ich habe bei mir ein zweites Konto eingerichtet und kann den Fehler nicht nachvollziehen. Mein erster Verdacht das Money-Money für beide Konten den gleichen Speicher verwendet hat sich nicht bestättigt, es wird sauber getrennt.
Ich hatte Deine Meldung aus den Issue mit dem Anmeldefehler verschoben, dort war das Problem das eine nicht behandelte Sicherheitsabfrage den Loginprozess stört. 
Bekommst Du auf den Handy bzw per eMail einen Link zur Bestättigung der Anmeldung?

**Comment by fazzer4x** [comment]
Pardon, gestern war es spät und ich habe mein issue nicht klar beschrieben.

Ich habe das gleiche Problem was den Abruf von den Kontodaten angeht. Auf meinen Konten habe ich kein 2FA aber bekomme den Hinweis per Mail bzw. in der App um den Prozess zu verifizieren.

**Comment by Michael-Beutling** [comment]
Alles klar.

Schalte bitte die 2FA bei Amazon ein, dann sollte der Spuk weg sein. 
Ist zum einen ein Tick sicherer und zum anderen kann das Plugin auch ungestört ohne User-Interaktion syncen.

**Comment by fazzer4x** [comment]
Funktioniert mit 2FA. Vielen Dank für die Hilfe!

**Comment by Hirsh** [comment]
Hatte das gleiche Problem. Danke für die Lösung mit der 2FA!
Wäre vielleicht eine Erwähnung in der README.md wert.

**Comment by Michael-Beutling** [comment]
Ist glaube ich gelöst, oder?
Ggf. neusten Release probieren. 
https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/release/amazon-orders.lua
