### ISSUE TITLE
to many http requests

### ISSUE THREAD

**Issue by joecomo67** [Michael-Beutling/Amazon-MoneyMoney#24]
Thank you very much for that great extension.

I have a lot of purchases (about 1500) and after about 500 I get an error from Amazon on two many http-requests.
I assume it would be good to limit the number of reads in one load process - that way I would require 
several runs to load everything the first time, but at least the downloads would complete.

I'll send you a screenshot of the error message as soon as I get the error again.
Yours Joachim

**Comment by joecomo67** [comment]
(weiter in Deutsch) - der Fehler behebt sich von selbst. MoneyMoney scheint die korrekt heruntergeladenen Zwischenergebnisse zu speichern. Nach ein paar Versuchen ist alles runtergeladen und die Daten sind da.
Das ist mal robust programmiert (egal von wem :))
Vielen Dank und viele Grüße Joachim

**Comment by Michael-Beutling** [comment]
Hallo,
konntest Du immer ~500 Bestellung pro Lauf nachladen oder musstest Du immer eine gewisse Zeit warten?

Gruß Micha

**Comment by joecomo67** [comment]
Hallo Michael,

 

genau so ist es – ich kann immer sofort eine neue Abfrage starten. 

Nach dem MoneyMoney lange genug versucht hat, bis die Zahl unter 
500 (ist eine ungefähre Schätzung – reale Zahl liegt zwischen 400 und 500) 
ist, klappt es am Ende und alle Buchungen sind da.

 

Die Fehlermeldung von Amazon selbst ist schwer zu kriegen -
ist ein Pop-Up, der schnell wieder weg ist.

 

Mit dem Workaround „öfter aktualisieren drücken“ funktioniert es
gut, ggf. reicht es den in der Read.me zu dokumentieren.

 

Vielen Dank und viele Grüße

 

Joachim

 

PS: Habe noch ein 2-tes Thema.

Versuche gerade auch mein US Konto auszulesen.
Habe eine separate LUA erzeugt und 

 

domain='.amazon.com',

services    = {"Amazon Orders US"},

 

entsprechend geändert. 
Im json war nichts, was sich auf das Domain bezieht.

Leider holt er auch mit „Amazon Orders US“ nur meine

deutschen Transaktionen ab. Werde mal genauer schauen,

was ich tun muss, damit das klappt – würde mich

aber über einen Tipp freuen.

 

Viele Grüße

 

Joachim

 

Von: Michael-Beutling <notifications@github.com>
Antworten an: Michael-Beutling/Amazon-MoneyMoney <reply@reply.github.com>
Datum: Mittwoch, 9. Dezember 2020 um 05:48
An: Michael-Beutling/Amazon-MoneyMoney <Amazon-MoneyMoney@noreply.github.com>
Cc: Joachim Seifert <joachim@seifert.eu>, Author <author@noreply.github.com>
Betreff: Re: [Michael-Beutling/Amazon-MoneyMoney] to many http requests (#24)

 

Hallo,
konntest Du immer ~500 Bestellung pro Lauf nachladen oder musstest Du immer eine gewisse Zeit warten?

Gruß Micha

**Comment by joecomo67** [comment]
Hallo Michael,

 

eine Hypothese: Kann es sein, dass alle lokalen Variablen im LUA Interpreter 
nur einmal belegt sind? Dann müsste ich die Namen ändern, um 

für die US-Abfrage eine andere URL zu haben.

 

Von: Joachim Seifert <joachim@seifert.eu>
Datum: Mittwoch, 9. Dezember 2020 um 09:29
An: Michael-Beutling/Amazon-MoneyMoney <reply@reply.github.com>, Michael-Beutling/Amazon-MoneyMoney <Amazon-MoneyMoney@noreply.github.com>
Cc: Author < author@noreply.github.com >
Betreff: Re: [Michael-Beutling/Amazon-MoneyMoney] to many http requests (#24)

 

Hallo Michael,

 

genau so ist es – ich kann immer sofort eine neue Abfrage starten. 

Nach dem MoneyMoney lange genug versucht hat, bis die Zahl unter 
500 (ist eine ungefähre Schätzung – reale Zahl liegt zwischen 400 und 500) 
ist, klappt es am Ende und alle Buchungen sind da.

 

Die Fehlermeldung von Amazon selbst ist schwer zu kriegen -
ist ein Pop-Up, der schnell wieder weg ist.

 

Mit dem Workaround „öfter aktualisieren drücken“ funktioniert es
gut, ggf. reicht es den in der Read.me zu dokumentieren.

 

Vielen Dank und viele Grüße

 

Joachim

 

PS: Habe noch ein 2-tes Thema.

Versuche gerade auch mein US Konto auszulesen.
Habe eine separate LUA erzeugt und 

 

domain='.amazon.com',

services    = {"Amazon Orders US"},

 

entsprechend geändert. 
Im json war nichts, was sich auf das Domain bezieht.

Leider holt er auch mit „Amazon Orders US“ nur meine

deutschen Transaktionen ab. Werde mal genauer schauen,

was ich tun muss, damit das klappt – würde mich

aber über einen Tipp freuen.

 

Viele Grüße

 

Joachim

 

Von: Michael-Beutling <notifications@github.com>
Antworten an: Michael-Beutling/Amazon-MoneyMoney <reply@reply.github.com>
Datum: Mittwoch, 9. Dezember 2020 um 05:48
An: Michael-Beutling/Amazon-MoneyMoney <Amazon-MoneyMoney@noreply.github.com>
Cc: Joachim Seifert <joachim@seifert.eu>, Author <author@noreply.github.com>
Betreff: Re: [Michael-Beutling/Amazon-MoneyMoney] to many http requests (#24)

 

Hallo,
konntest Du immer ~500 Bestellung pro Lauf nachladen oder musstest Du immer eine gewisse Zeit warten?

Gruß Micha

**Comment by joecomo67** [comment]
Have jetzt die Debug Info gesehen - auch wenn ich den Service umbenenne, wird immer dasselbe Skript aufgerufen.
Ich versuche mein US Account mal auf einem anderen Rechner.

**Comment by joecomo67** [comment]
Beim US Account bekomme ich eine Captcha Anfrage, danach wird aber nicht das 2FA Token abgefragt und es gibt einen Abbruch wg. falschem Password.
Bei meinem französischen Account bekomme ich die korrekte 2FA Abfrage und die Daten werden geladen - allerdings kann das Skript diese (sprachbedingt) nicht auswerten.

**Comment by Michael-Beutling** [comment]
Das einloggen bei Amazon war etwas knifflig, größte Baustelle war die Zeile 303:
` if  i:sub(1, #'ap-fid=') ~= 'ap-fid=' and i:sub(-#'=deleted') ~= '=deleted' then` 
Damit wird dem Cookie-Handling in MoneyMoney  auf die Sprünge geholfen. Beide Cookies wurden im Request mit zurückgegeben und triggerten u.a. das Captcha.

Neben dem Cache für die Bestellungen, gibt es noch einen webCache der die ganze Seite speichert, damit kann u.a. sich mit einen Browser die Seiten die MoneyMoney abruft ansehen. 

Zum französischen: Bis auf die Monatsangabe (str2date) sollte keine Sprachabhängigkeit enthalten sein. Wenn die Datumserkennung klappt, sollten bei gleichen HTML-Layout (xpath) Bestellungen einlaufen.

**Comment by joecomo67** [comment]
ich habe jetzt auch amazon.co.uk probiert - der Login und die Kontenidentifikation klappt bestens. Ich sehe auch wie die Anwendung durch alle Jahre geht - aber am Ende kommen (wie auch in Frankreich) keine Transaktionen an.
Habe in dem Container nach den Caches gesucht und auch im JSON debugging eingeschaltet (File mit 0Byte wird erzeugt).
Weiter komme ich dann aber nicht - komisch.

**Comment by joecomo67** [comment]
Leider kann ich keinen der Caches unter ~/Library/Containers/com.moneymoney-app.retail/Data finden - ist mir ein Rätsel, wo die Daten sind

**Comment by Michael-Beutling** [comment]
Der webCache wird mit den script webCache_on.sh gestartet. Damit sollte der Ordner webCache angelegt werden. Der Debugschalter "debug" muss true sein. Dafür die Datei ~/Library/Containers/com.moneymoney-app.retail/Data/amazon_orders.json mit folgenden Inhalt anlegen:
`{"configOk":true,"cleanInvalidCache":false,"debug":true,"cleanFilterCache":false,"reallyLogout":true,"cleanCookies":false,"cleanOrdersCache":false}`

Jetzt sollte der webCache starten, lohnt sich aber zunächst nur bei den Accounts wo das Script sauber ohne 2FA u.ä. durchläuft.

Der Cache für die Bestellungen ist in der MoneyMoney Datenbank und nicht ohne weiteres nur für das Script per LocalStorage zugänglich.

Jetzt kommt der hässliche Teil, wenn Bestellungen gefunden (das war noch was bei Dir geklappt hat?) werden (Statustext "Get details for order xxx-xxxx") wird getOrderDetails aufgerufen, dort wird die Detailseite einer Bestellung aufgerufen und geprüft ob im xpath //div[@id="orderDetails"] Text enhalten ist. Jetzt muss man sich immer an den zweifelhaften Stellen immer eine print Anweisung einbauen und schauen ob dort die passenden Daten gefunden wurden bzw. ob eine Prüfung geklappt hat.
Kommen nicht gewünschten Daten sind meist die xpath Angaben schuld. Mit dem Debug tools im Browser kann man die xpath Angaben einfach prüfen. In der Console z.B.  sollte der Details xpath $x('//div[@id="orderDetails"]')  in der Bestelldetailansicht den ganzen Kasten für die Bestellung markieren. 
Mit einen Side-by-Side Vergleich mit dem deutschen Amazon sollest Du gut die anzupassenden xpath Ausdrücke finden.

**Comment by joecomo67** [comment]
Vielen Dank für die Hinweise - werde mir das nun genauer anschauen, die Infos sollten
erstmal reichen.
Können eigentlich auch andere Variablen in dem json belegt werden (z.B. const.domain)?

**Comment by joecomo67** [comment]
So die französischen und englischen Seiten kriege ich jetzt hin - hierzu musste ich den mapping table um die französischen Monatsnamen ergänzen und die Regexp für die jeweilige Währung anpassen.
Damit man alles in einem MoneyMoney Account nutzen kann, habe ich extra Versionen à la "Amazon GB Orders" erzeugt, die man auswählen muss. Ziemlich schmutziger Hack - funktioniert aber.

Die US Seite hat ein anderes Problem - während die Europäischen Seiten vom Login Vorgang identisch sind, ist hier etwas anders. Es kommt immer die Captcha Abfrage - diese erfordert die Wiedereingabe des Passworts UND das Captcha. Ich bin mir ziemlich sicher, dass das Script *nur* das Captcha liefert. Dann bricht es mit "falsches Passwort" ab und erreicht nie die 2FA Token Abfrage.

Leider ist der Code da ziemlich complex - wenn Du Lust hast kannst Du Dir das anschauen, geht sicher schneller.

Vielen Dank und viele Grüße Joachim

(Hab mein angepasstes "Amazon US Orders" script beigefügt - geändert ist nur die Regexp, das Monats-Mapping, den Namen des jsons/debug-files  und die Registrierung des Protokolls in MoneyMoney.)

[amazon-us-orders.lua.zip](https://github.com/Michael-Beutling/Amazon-MoneyMoney/files/5683853/amazon-us-orders.lua.zip)
