### ISSUE TITLE
Umsätze werden nicht geladen

### ISSUE THREAD

**Issue by andreasarndt** [Michael-Beutling/Amazon-MoneyMoney#26]
Hallo Michael,

zunächst mal vielen Dank für das Plugin - das hat echt gefehlt!

Leider funktioniert es bei mir nicht - die Umsätze werden nicht geladen. Mein Amazon-Konto besteht seit 20 Jahren und ich habe ca. 1050 Bestellungen. Die Bestellungen werden bis ca. 800 oder 900 geladen, dann bricht der Vorgang einfach ab.

Toll wäre, wenn man die Jahre / Monate einschränken könnte, ab denen die Bestellungen geladen werden - die alten interessieren ja eigentlich  nicht so.

Viele Grüße,
Andreas.

**Comment by Michael-Beutling** [comment]
Wenn möglich (beta-Version verfügbar) kannst Du die master testen, die limitiert die Anzahl der Abfragen.

**Comment by Michael-Beutling** [comment]
Sollte mit https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/release/amazon-orders.lua gelöst sein.
