### ISSUE TITLE
No data after Feb 15th

### ISSUE THREAD

**Issue by pepe82sh** [Michael-Beutling/Amazon-MoneyMoney#27]
I'm very happy with this awesome plugin! It just seems that since Feb 15, no data is synced. I get no error message or anything close to it. When syncing I get the following states:

- Lade Kontostand und Umsätze für Amazon...
- Get order overview for 'letzte 3 Monate'
- _Something that appears and disappears to quick to be read_

No new orders are added, even though there are some on the amazon web interface.

Are there any log files I could check out? Found none and google did not help.

Thanks heaps!

**Comment by andre68723** [comment]
you can retrieve the logs via "Fenster->Protokoll"

sample
```
          1> Get order overview for "letzte 3 Monate"
          1> Sending: GET https://www.amazon.de/gp/your-account/order-history?opt=ab&digitalOrders=1&unifiedOrders=1&returnTo=&__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&orderFilter=months-3
```

BTW I have a similar issue - version here is ```WebBanking{version  = 1.14,```
The last 6 purchases after Feb 25th are not displayed. 

More specifially, anything behind a order which I returned ( "Rücksendung begonnen
Ihre Gutschrift wird bearbeitet, wenn wir Ihren Artikel empfangen." ) is displayed, anything before that (=newer) not including the returned order

Thanks, Andre

**Comment by Michael-Beutling** [comment]
When You have a beta version from MoneyMoney, You can give the master a try.

**Comment by pepe82sh** [comment]
I checked the log, and the newer data is at least contained in Amazons response. So it might be a parser issue or something along those lines. I just switched to beta and will give the master a try.

**Comment by pepe82sh** [comment]
Master did work, thanks a lot!
Are you planning on releasing a new signed version soon?

**Comment by Michael-Beutling** [comment]
Thanks for the feedback. I give the version to sign.

**Comment by pepe82sh** [comment]
Thanks for the quick response and solution :)

**Comment by Michael-Beutling** [comment]
signed version https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/release/amazon-orders.lua
