### ISSUE TITLE
amazon-orders.lua:233: bad argument #1 to 'request' (string expected, got nil)

### ISSUE THREAD

**Issue by pinguinpfleger** [Michael-Beutling/Amazon-MoneyMoney#3]
Hallo, ich bekomme folgenden Fehler
```
[...]
19:12:04  Sending: GET https://www.amazon.de/gp/css/order-history?ie=UTF8&ref_=nav_orders_first&
19:12:07  Received: [...]
19:12:09  Web Banking account: Amazon Unkown (mix)
          Web Banking account: Amazon Unkown (normal)
          Web Banking account: Amazon Unkown (inverse)
          Lade Kontostand und Umsätze für Amazon Unkown ...
          Getting transactions since 03.04.2019...
          Refresh mix
          Received 1 transaction, 1 is new.
          Lade Kontostand und Umsätze für Amazon Unkown ...
          Getting transactions since 03.04.2019...
          Refresh normal
          Received 1 transaction, 1 is new.
          Lade Kontostand und Umsätze für Amazon Unkown ...
          Getting transactions since 03.04.2019...
          Refresh inverse
          amazon-orders.lua:233: bad argument #1 to 'request' (string expected, got nil)
```

**Comment by Michael-Beutling** [comment]
Hallo,
ich vermute das der Anmeldeprozess schiefgegangen ist, nach dem "Refresh inverse" kommt nämlich ein Logoff und da fehlt der Abmelde-Link. Außerdem konnte Dein Amazonname nicht ermittelt werden (Unkown).
Das Konto löschen und neu Anlegen hast Du vermutlich schon gemacht.
Wenn Du im Browser die Amazon Cookies löscht und Dich anmeldest wie läuft der Prozess ab?
Idealerweise aktivierst Du in Safari den Entwicklermodus und deaktiviert im Entwicklermenü Javascript/Styles. Dann läuft die Anmeldung genauso wie im Script.  

Bei mir sieht das so aus:  
Anmelden mit Benutzername/Passwort
Zwei-Schritt-Verifizierung mit OTP

Welche Schritt kommen bei Dir?
Gruß Micha

**Comment by pinguinpfleger** [comment]
In der Reihenfolge, ja. Login dann 2FA Token.
Bei 19:12:07  Received: [...] kommt der HTML Quelltext. 
Als HTML Datei gespeichert wird wird die Seite im Browser korrekt angezeigt, mit den letzten Bestellungen.

**Comment by Michael-Beutling** [comment]
Okay, Du bist sauber eingeloggt. 

Ruf mal bitte die Amazon mit Safari auf und aktiviere das Entwickler Menü
Wenn Du im Browser Du links oben "Hallo ... / Konto und Listen" mit Rechtsklick
 das Element untersuchst sollte Dein Name dort zu finden sein.
Beispiel: `<span class="nav-line-3">Michael</span>`
Was steht da bei Dir für die Class?

Wenn Du das Menü aufklappen lässt unter "Hallo ... / Konto und Listen", sollte ganz unten Abmelden stehen, auch dieses Element bitte untersuchen.

Beispiel: `<a href="/gp/flex/sign-out.html?ie=UTF8&amp;action=sign-out&amp;path=%2Fgp%2Fyourstore%2Fhome&amp;ref_=nav_youraccount_signout&amp;signIn=1&amp;useRedirectOnSuccess=1" class="nav-link nav-item" id="nav-item-signout"><span class="nav-text">Abmelden</span></a>`

**Comment by fiaskogaul** [comment]
Hab das gleiche Problem, allerdings nur am Business Account. Der Private Account läuft.

Interessanter Weise sieht der Beriech "links oben "Hallo ... / Konto und Listen" im Business Account anders aus:

`<span class="abnav-accountfor">Konto für Firmenname </span>`

bzw.

`<span class="nav-line-2"><span class="abnav-accountfor">Konto für Firmenname </span><span class="nav-icon nav-arrow" style="visibility: visible;"></span></span>
`

"Firmenname" habe ich geändert. "Konto für" steht so aber im Quelltext.

**Comment by fiaskogaul** [comment]
Hier mal noch mein verkürztes Übertragungsprotokoll. Ich habe das Gefühl die Anmeldung klappt aber dann geht was schief:

```
10:51:18  Started MoneyMoney [Retail] version 2.3.24 (348) on macOS 10.15.4.
          Application file: /Applications/MoneyMoney.app
          Database file: /Users/fiaskogaul/Library/Containers/com.moneymoney-app.retail/Data/Library/Application Support/MoneyMoney/Database/MoneyMoney.sqlite
          Database created on 23.11.2015.
          Bank server settings from 03.04.2020.
10:51:21  config read...
          Amazon Orders plugin loaded...
10:51:30  Starting account setup assistant.
10:51:57  Lade Kontenliste ...
          Web Banking Engine: Using user-supplied extension amazon-orders.lua version 1.07.
          clean caches...
          signed Amazon Orders plugin loaded...
          Protocol version: Web Scraping
          Server address: https://www.amazon.de
          Sending: GET https://www.amazon.de
          Received: (...)
          Sending: GET https://www.amazon.de/gp/css/order-history?ref_=nav_orders_first
          Sending: GET https://www.amazon.de/ap/signin?_encoding=UTF8&accountStatusPolicy=P1&openid.assoc_handle=deflex&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.de%2Fgp%2Fcss%2Forder-history%3Fie%3DUTF8%26ref_%3Dnav_orders_first&pageId=webcs-yourorder&showRmrMe=1
          Received: (...)
          enter username/password
          Sending: POST https://www.amazon.de/ap/signin
10:51:58  Sending: GET https://www.amazon.de/ap/mfa?ie=UTF8&arb=55537f20-4746-4afe-b97a-ad747f1a989d&mfa.arb.value=55537f20-4746-4afe-b97a-ad747f1a989d&mfa.arb.key=arb
          Received: (...)
          Challenge: Geben Sie den Code ein, der von Ihrer Authentifizierungs-App erzeugt wurde
          Asking user for two-factor authentication.
10:52:04  Sending: POST https://www.amazon.de/ap/signin
10:52:05  Sending: GET https://www.amazon.de/gp/css/order-history?ie=UTF8&ref_=nav_orders_first&
10:52:08  Received: (...)
          Web Banking account: Amazon Unkown (mix)
          Web Banking account: Amazon Unkown (normal)
          Web Banking account: Amazon Unkown (inverse)
          Lade Kontostand und Umsätze für Amazon Unkown ...
          Getting transactions since 05.04.2019...
          Refresh mix
          Received 1 transaction, 1 is new.
          Lade Kontostand und Umsätze für Amazon Unkown ...
          Getting transactions since 05.04.2019...
          Refresh normal
          Received 1 transaction, 1 is new.
          Lade Kontostand und Umsätze für Amazon Unkown ...
          Getting transactions since 05.04.2019...
          Refresh inverse
          amazon-orders.lua:233: bad argument #1 to 'request' (string expected, got nil)
```

**Comment by pinguinpfleger** [comment]
Hab mir den Quelltext etwas genauer angesehen, lua ist ja witzig und was mit Connection() alles geht, sogar clicks und so. Dafür werde ich sicher auch mal Verwendung finden.

Also ich hab mich an einem fix versucht aber ...
> 12:51:16  Ignoring 'amazon-orders.lua' because signature verification failed.

```
 if html:xpath('//*[@id="timePeriodForm"]'):attr('id') == 'timePeriodForm' then
    aName=html:xpath('//span[@class="nav-line-3"]'):text()
    if aName == "" then
      -- try business account 
      aName=html:xpath('//span[@class="nav-line-2"]'):text()
      if aName == "" then
        aName="Unkown"
        -- print("can't get username, new layout?")
      else
        -- print("name="..aName)
      end
    end
  else
    LocalStorage.cookies=nil
    return LoginFailed
  end
```

https://github.com/Michael-Beutling/Amazon-MoneyMoney/blob/master/amazon-orders.lua#L494

Ich denke es würde der Übersicht und Wartbarkeit dienen die xpath selektoren in einem Abschnitt zu definieren, für die unterschiedliche "Versionen"

**Comment by pinguinpfleger** [comment]
ok [hier](https://moneymoney-app.com/api/webbanking/) wird erklärt das man in den beta Versionen von MoneyMoney die Signaturprüfung in der Einstellungen abschalten kann.

**Comment by pinguinpfleger** [comment]
ok der Name wird damit angezeigt aber der Fehler ist damit nicht behoben...

**Comment by pinguinpfleger** [comment]
> Beispiel: `<span class="nav-line-3">Michael</span>`
> Was steht da bei Dir für die Class?

```html
<a href="/gp/css/homepage.html?ie=UTF8&amp;ref_=bnav_youraccount_btn" class="nav-a nav-a-2 nav-truncate" data-nav-ref="nav_ya_signin" data-nav-role="signin" id="nav-link-yourAccount" tabindex="61">
  <span class="nav-line-1">Hallo, Kai</span>
  <span class="nav-line-2">
    <span class="abnav-accountfor">Konto für ####### </span><span class="nav-icon nav-arrow" style="visibility: visible;"></span>
  </span>
</a>
```

> Wenn Du das Menü aufklappen lässt unter "Hallo ... / Konto und Listen", sollte ganz unten Abmelden stehen, auch dieses Element bitte untersuchen.


```html
<a href="/gp/flex/sign-out.html?ie=UTF8&amp;action=sign-out&amp;path=%2Fgp%2Fyourstore%2Fhome&amp;ref_=nav_youraccount_bnav_ya_ad_so&amp;signIn=1&amp;useRedirectOnSuccess=1"
 class="nav-link nav-item" id="nav-item-signout">
<span class="nav-text">Abmelden</span> 
</a>
```
wenn reallyLogout false ist kommt der Fehler nicht.
ich bekomm es aber nicht hin
```lua
html= connectShop(html:xpath('//a[contains(@href,"signout")] | //a[contains(@href,"sign-out")] | //a[@id="nav-item-signout"]'):click())
```
funktioniert nicht.

**Comment by Michael-Beutling** [comment]
Das sollte den Logout-Fehler beheben: [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue3/amazon-orders.lua)

Für die Erkennung des Benutzernamens habe ich hoffentlich was allgemein gültiges gefunden.

**Comment by pinguinpfleger** [comment]
nicht wirklich, ;-)
1. wenn die element variable nil ist soll click angewendet werden. Du meintest ungleich statt gleich.
2. ausgeloggt werden die business accounts dann nie
```lua
function EndSession ()
  -- Logout.
  if config['reallyLogout'] then
    local logoutElement=html:xpath('//a[@id="nav-item-signout"]')
    if logoutElement == nil then
      html= connectShop(logoutElement:click())
    else
      print("error: logout link not found")
    end
  end
end
```

**Comment by Michael-Beutling** [comment]
Letzter Schuss: 
[amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue3/amazon-orders.lua)

Ich mache heute Schluß bevor ich noch versehentlich die Matrix lösche...

**Comment by Michael-Beutling** [comment]
neue Version [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue3/amazon-orders.lua)

Feedback?

**Comment by ChrisKor** [comment]
Hallo, 

sorry für die NewBee-Frage, aber vielleicht bekomm ich trotzdem ne Antwort. Wie bekomme ich aus deiner gepusteten Datei ein Laufendes Script für MoneyMoney? Ich hab das oben beschriebene Problem und bekomme auf der MoneyMoney-Seite aber noch eine alte Version. Ich würde es gerne ausprobieren, aber mit dem Link in diesem Post lade ich nur eine .txt Datei.

Vielen Danke für die Hilfe.
Frohe Ostern
Chris

**Comment by Michael-Beutling** [comment]
Es gibt eine Beta [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/beta/amazon-orders.lua)

@ChrisKor 
Die Dateiendung auf .lua ändern, bzw. mit Rechtsklick und "Link speichern unter" kann man den Dateinamen entsprechend ändern.
Das Plugin von Github läuft aber nur wenn Du eine Beta von MoneyMoney hast und die Signaturprüfung ausschaltest.

**Comment by ChrisKor** [comment]
Hi, danke. Das mit der Beta-Version von MoneyMoney wird das Problem gewesen sein. Hab die Dateiendung schon geändert gehabt und korrekt verschoben, aber halt mit der "offiziellen" Version. Dann lädt das Plug-In einfach nicht.

Danke, und danke für dein Plug-In
Chris
