### ISSUE TITLE
Problem mit Zwei-Faktor-Authentifizierung

### ISSUE THREAD

**Issue by fbreuer1** [Michael-Beutling/Amazon-MoneyMoney#31]
Hallo, erst einmal vielen Dank für das fantastische Plugin das ich nun über Jahre hinweg gerne genutzt habe.
Leider habe ich aber nun folgendes Problem: Amazon hat mich vor kurzem dazu aufgefordert mein Passwort zu ändern (wirklich, kein Phishing :)), was nun allerdings dazu führt, dass ich beim Login noch mal Passwort + Captcha eingeben soll.

Wie auf folgendem Screenshot zu sehen, existiert zwar das Feld für das Captcha, nicht jedoch für das Passwort, sodass die Abfrage zwangsläufig scheitert. Ist es möglich, hier auch das zweite Feld einzublenden?

<img width="522" alt="Bildschirmfoto 2022-01-15 um 12 08 59" src="https://user-images.githubusercontent.com/38318487/149619623-4a089e0c-d405-42d6-b5df-31ee4e50e53a.png">

**Comment by Michael-Beutling** [comment]
Hallo,
Hast Du die Zugangsdaten für das Konto schon auf das neue Passwort geändert? (rechte Maustaste auf das Konto in der Seitenleiste)
Dann sollte nur nach dem Captcha gefragt werden. 
Die Dialoge von MoneyMoney sind vorgegeben, ein zweites Eingabefeld ist nicht vorgesehen.

**Comment by fbreuer1** [comment]
Wow, das ist mal eine schnelle Antwort! Ja, das Passwort habe ich schon aktualisiert, im Web-Login kam beim ersten Anmelden ebenjene Abfrage schon einmal (explizit nach dem Login 2. mal Passwort + Captcha).

**Comment by fbreuer1** [comment]
Derselbe Dialog erscheint im übrigen auch, wenn ich einfach das Aktualisieren des Kontos erzwingen will:

<img width="401" alt="Bildschirmfoto 2022-01-15 um 12 26 29" src="https://user-images.githubusercontent.com/38318487/149620112-3cd5b7f7-c7e9-4a76-81de-970e4d5bdd25.png">

**Comment by Michael-Beutling** [comment]
Konnte den Dialog erzwingen und jetzt wird das Passwort-Feld gefüllt. Skript liegt auf dem Master, falls Du keine Beta-Version von MoneyMoney hast, muss Du Dich mindestens bis Montag gedulden für die signierte Version.

**Comment by Michael-Beutling** [comment]
signierte Version https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/release/amazon-orders.lua

**Comment by DiDab-GH** [comment]
Hallo, ich habe ein ähnliches Problem. Nachdem Amazon mich in den letzten Wochen mehrmals zu einer Änderung meines Passwortes genötigt hat (jeweils nach Abfrage über das Plugin), habe ich jetzt 2FA aktiviert.
Die Anmeldung über das Plugin funktioniert weiterhin nicht, sondern scheitert am Ende (nach Eingabe des OTP) mit

> Ihre Zugangsdaten (E-Mail-Adresse, Passwort) wurden vom Server Ihrer Bank als ungültig abgewiesen. Bitte überprüfen Sie noch einmal Ihre Zugangsdaten.

und dem Hinweis im Protokoll

> login failed, clean cookies
