### ISSUE TITLE
Passwortabfrage

### ISSUE THREAD

**Issue by jsadbjsadljnsa** [Michael-Beutling/Amazon-MoneyMoney#32]
Hallo Michael,

ich bekomme immer eine Aufforderung zur Eingabe meines Passwortes, obwohl dieses nicht geändert wurde.

Wenn ich das Passwort nun eingebe, so sagt mir MoneyMoney, dass mein Passwort falsch sei (über den Browser kann ich mich aber bei Amazon einloggen).

Hast du hier eine Idee?

VG Bernd

**Comment by Michael-Beutling** [comment]
Hallo Bernd,

aktuell funktioniert bei mir alles, mit und ohne otp jeweils mit neuen und alten Konto.
Vermutlich dauert wieder es ein paar Tage bis die "Neuigkeit" bei allen Kunden ausgerollt ist, dann kann ich das debuggen.
Bitte gedulden.

Gruß Micha

**Comment by jsadbjsadljnsa** [comment]
Hi Micha, hat geklappt, danke dir!!
