### ISSUE TITLE
Ihre Zugangsdaten (E-Mail-Adresse, Passwort) wurden vom Server Ihrer Bank als ungültig abgewiesen. Bitte überprüfen Sie noch einmal Ihre Zugangsdaten.

### ISSUE THREAD

**Issue by confluencepoint** [Michael-Beutling/Amazon-MoneyMoney#33]
Ich würde gern das Issue aus: https://github.com/Michael-Beutling/Amazon-MoneyMoney/issues/31#issuecomment-1040077020 hier fortsetzen.

Meldung:
> Ihre Zugangsdaten (E-Mail-Adresse, Passwort) wurden vom Server Ihrer Bank als ungültig abgewiesen. Bitte überprüfen Sie noch einmal Ihre Zugangsdaten.

Seit gestern (15-02-2022) scheint _Amazonk_ irgendwas geändert zu haben. Selbst mit **_deaktivierten_** OTP ist **kein** Login mehr möglich.

**Comment by Michael-Beutling** [comment]
Hallo,

aktuell funktioniert bei mir alles, mit und ohne otp jeweils mit neuen und alten Konto.
Vermutlich dauert wieder es ein paar Tage bis die "Neuigkeit" bei allen Kunden ausgerollt ist, dann kann ich das debuggen.
Bitte gedulden.

Gruß Micha

**Comment by joecomo67** [comment]
ich habe dasgleiche Problem - allerdings nur in einigen meiner Amazon-Konten.
Spricht dafür, dass es sich um eine schrittweise Umstellung handelt

**Comment by Michael-Beutling** [comment]
Hallo,
ein  Nutzer hat mir einen Patch geschickt für das neue Layout. Wer eine Beta von MoneyMoney am Start hat, kann die unsignierte Version mal ausprobieren, Danke.

**Comment by Michael-Beutling** [comment]
Eine signierte Version: https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/release/amazon-orders.lua

**Comment by joecomo67** [comment]
das ging ja schneller als erwartet - Vielen Dank.

Noch ein Tipp - Amazon US hat mittlerweile eine Datenschutzseite (siehe https://www.komando.com/how-tos/ways-to-download-your-amazon-order-history/752778/)- da kann man seine ganze Order History bestellen (man bekommt dann per Email einen download link). Man bekommt auch die Daten für alle internationalen Seiten gleich mit und das Datenmodell ist wirklich sehr ausführlich.

Alles etwas umständlich - aber eine gute Ergänzung zum MoneyMoney Plug-In.

**Comment by DiDab-GH** [comment]
> Eine signierte Version: https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/release/amazon-orders.lua

Anmeldung klappt wieder. Vielen Dank.

**Comment by Michael-Beutling** [comment]
Danke für den Hinweis. 
Witzigerweise waren zwei Reports bei mir schon drin, an die ich mich aber garnicht erinnern konnte. Nachdem ich aktuelle Reports angefordert hatte, war mir auch klar warum ich sie vergessen hatte: 0 Einträge.
