### ISSUE TITLE
Versandkosten bei Orders ohne kostenlosen Versand werden nicht importiert

### ISSUE THREAD

**Issue by trulyarya** [Michael-Beutling/Amazon-MoneyMoney#34]
Hallo Michael!

erstmal vielen Dank für diese Extension.

Ich habe das Ding seit gestern ausprobiert und sehe, dass bei einem Artikel, der z.B. 5€ + 3,99€ Versand kostet, nur der Artikelpreis in MoneyMoney importiert wird. Das heißt:

```
17.02.2022      304-5179056-6898707
                Knoblauchpresse                                                     -5,00€
                Reference: Name, address - Value date: 03.03.2022
                Account: First name, Last name 
```

Die 3,99€ Versandkosten tauchen nie auf.

Danke schonmal!

**Comment by Michael-Beutling** [comment]
Hallo,

die Versandkosten sollten als `Difference (shipping costs, coupon etc.)` gebucht werden. Ist das nicht der Fall?

Gruß Micha
