### ISSUE TITLE
Viele Ei> Scrreenshot

### ISSUE THREAD

**Issue by pragmat1c1** [Michael-Beutling/Amazon-MoneyMoney#35]

**Comment by pragmat1c1** [comment]
Hallo, erstmal vielen Dank fuer das Plugin! Super nuetzlich!

Habe gerade Einkaeufe seit 2020 importiert, sehe viele Zeilen, die mit "Difference (shipping costs, coupon etc.)" markiert sind.

Wenn ich im Code suche, sehe ich:

```lua
     if order.orderSum ~= order.orderTotal then    # <======
        table.insert(transactions,{
          name=orderCode,
          amount = (order.orderTotal-order.orderSum)/divisor,
          bookingDate = order.bookingDate,
          purpose = const.differenceText,    # <=====
          endToEndReference = order.endToEndReference,
          accountNumber = order.accountNumber,
          bookingText=order.bookingText,
        })
      end
```

**Comment by Michael-Beutling** [comment]
Hallo,

hier wird die Differenz zwischen Summe aller Positionen einer Bestellung und der Gesamtsumme ausgewiesen. Hier könnte man noch etwas Arbeit reinstecken und den Bestellkopf parsen, allerdings wird das knifflig weil auch Umsatzsteuer usw. aufgeführt sind und ein einfaches Zusammenrechnen nicht geht. 
Auf einzelne Bestellpositionen kann das nicht runtergebrochen werden, die Information ist im Bestellkopf für alle Positionen der Bestellung.
Wenn Du den Text global ändern möchtest, kannst Du in den Einstellungen für das Konto unter Notizen ein Attribut mit den Namen `differenceText` setzen. Der Attributwert überschreibt dann den `const.differenceText` Text.

Falls Du die Differenz auf einzelne Positionen verrechnen möchtest, sollte das Notfalls in MoneyMoney mit Split und Umsatz bearbeiten gehen. 

Gruß Micha
