### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by janstieler** [Michael-Beutling/Amazon-MoneyMoney#36]
Hallo,
im Log Fenster von MoneyMoney steht `Ignoring 'amazon-orders.lua' because signature verification failed.`
Wie kann ich die Signatur der Extension verifizieren?

Grüße

**Comment by Michael-Beutling** [comment]
Hallo,

vermutlich hast Du die Version aus dem Master Branch, dort ist die Entwicklerversion. Die signierte Version liegt im Release-Branch https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/release/amazon-orders.lua oder auf der Homepage von MoneyMoney https://moneymoney-app.com/extensions/amazon-orders.lua .

Gruß Micha

**Comment by janstieler** [comment]
Hallo,

danke für die schnelle Antwort.
Ja war wohl die Master. Jetzt zeigt er mir `Amazon Orders plugin loaded...; lua debug is usable`.

Gruß Jan
