### ISSUE TITLE
Keine Bestellungen oder Transaktionen

### ISSUE THREAD

**Issue by janstieler** [Michael-Beutling/Amazon-MoneyMoney#37]
Hallo,

ich hab das Problem das bei mir keinerlei Bestellungen angezeigt werden.
Ich sehe im Log wie die Daten abgerufen werden aber überall kommt die Meldung 
```
0 orders from messages
1> Received 0 transactions.
```
Das Plugin geht bis 2019 zurück und in den letzten Jahren wurden auch Sachen bestellt.
Die letzten Anfang diesen Jahres.

Das Konto ist ein Amazon Business Konto, falls das relevant ist.

Viele Grüße

**Comment by Fernsehstuhl** [comment]
Bei mir ähnlich, normale Bestellungen werden nicht geladen. Allerdings sämtliche "Abos" bzw. Medien. 
- Audible
- Gekaufte Filme

Woran könnte es liegen, dass die normalen Bestellungen nicht angezeigt/runtergeladen werden?

**Comment by Michael-Beutling** [comment]
Hallo,

Geschäftskonten werden nur rundimentär unterstützt. Seht Ihr im Log `work-around, see issue #21`?

Problem wäre dann der vorgeschaltete Dialog um das passende Unterkonto auszuwählen.

Gruß Micha

**Comment by Fernsehstuhl** [comment]
Mhm...woran erkenne ich, ob ich ein BusinessKonto habe? Habe ich aus meiner Sicht nicht...habe aber schon mal was über Amazon verkauft. Also vielleicht doch?

**Comment by janstieler** [comment]
Hi,
das erkennt man unter anderem an dem dicken Business Logo links oben.


Oder wenn Du rechts auf Deinen Namen gehst siehst im Dropdown-Menü ein Punkt »Firmenkonto verwalten«.
Das ganze Design ist dunkler als das normale Amazon.

**Comment by Fernsehstuhl** [comment]
Alles nicht zutreffend...habe dann wohl kein BusinessKonto und das alte Verkaufskonto zumindest löschen lassen.
