### ISSUE TITLE
Keine Bestellungsdaten seit 25.3.

### ISSUE THREAD

**Issue by Helmi** [Michael-Beutling/Amazon-MoneyMoney#39]
Hi,

mein Konto hat sauber abgerufen. Seit 25.3. kommen keine Daten mehr obwohl Bestellungen vorhanden sind. Heute habe ich ein zweites Amazon-Konto zum abruf eingerichtet von dem gar keine Daten kommen.

Abruf erfolgt fehlerfrei, "Please reload and drink a coffee" verschwindet nach dem Abruf, aber es kommen keine Daten.

Hat es möglicherweise Änderungen bei Amazon gegeben die irgendwas kaputt gemacht haben?

Ich verwende Extension Version 1.17

**Comment by Helmi** [comment]
Nachtrag: Ich habe die Beta und Latest-Versionen getestet. Mit der Beta gab es Authentifizierungsprobleme (Account mit 2FA), mit der Latest hat es wieder geklappt, leider werden dennoch keine Bestellungen abgerufen. Laut Log wird durch die Seiten gepaged aber am Ende bleiben immer "0 orders from messages /n Logout"

Es handelt sich übrigens bei beiden Accounts um normale Amazon-Accounts (kein Business, kein Verkäufer, einer von beiden mit Prime, der andere ohne).

**Comment by Helmi** [comment]
@Michael-Beutling danke, der fix scheint das Problem zu beheben. Allerdings hab ich das Problem, dass ich vom neu hinzugefügten Konto nur die Daten vom letzten viertel Jahr bekomme - offenbar weil das Plugin glaubt schon mal erfolgreich Daten abgerufen zu haben. Kann ich eine "vollständige Abfrage" erzwingen?

**Comment by Michael-Beutling** [comment]
Unter Konteneinstellungen/Notizen das Attribunt `resetCache` auf einen Wert setzen, z.b. Tagesdatum. 
Immer wenn der Wert geändert wird, wird der Cache gelöscht und das ganze Konto neu eingelesen.

**Comment by berti2911** [comment]
Hi, ich hatte das gleiche Problem und die gefixte Version hat anschließend funktioniert - vielen Dank dafür.
Und zusätzlich ein dickes Kompliment an diese Extension, die spart mir einiges an Arbeit.
