### ISSUE TITLE
Falscher Betrag bei Teilrücklieferung

### ISSUE THREAD

**Issue by Michael-Beutling** [Michael-Beutling/Amazon-MoneyMoney#4]
> Ich habe mal nach einer Retoure gesucht, die erscheint als negativer Betrag mit einer entsprechenden Konterbuchung.

Ich habe noch eine zweite rausgesucht, die wird falsch erkannt: In der Bestellung sind zwei Artikel, einer davon wurde zurückgeschickt, in den Umsätzen erscheinen beide negativ mit einer positiven Konterbuchung. Das sieht auf der Amazon Webseite aber auch irreführend aus, dass nur einer erstattet wurde.

_Originally posted by @bwess in https://github.com/Michael-Beutling/Amazon-MoneyMoney/issues/2#issuecomment-607762512_

**Comment by Michael-Beutling** [comment]
Screenshots von Amazon und von MoneyMoney wären toll. Mir fehlt gerade die Vorstellung wie das aussieht, Danke.

**Comment by Michael-Beutling** [comment]
Danke für die Screenshots,
ich könnte den "Status der..." Button auswerten, der verweist auf eine ".../returns/..." URL.
Meine Retouren wurden nicht erstattet, sondern ersetzt:
![Bildschirmfoto](https://user-images.githubusercontent.com/2708948/78322567-65535080-756f-11ea-818e-9391c1b32684.png)

Bei mir gibt es eine URL mit der Ersatzlieferung und den Text "Ersatz beantragt".
Bei Dir steht vermutlich "Rückerstattung" und es fehlt die URL für die Rücksendung.
Falls das bei Dir steht o.ä. kannst Du mit den Entwicklerwerkzeugen Deines Browser Dir den HTML-Code vom Element ansehen?
Sollte ähnlich wie bei mir aussehen: `<span class="a-size-base a-text-bold">Ersatz beantragt</span>`

**Comment by bwess** [comment]
Eigentlich müsste es dann eine Konterbuchung für die zurückgeschickten und eine für die gekauften Artikel geben...

Hier das HTML der Details Seite:
![Details HTML](https://user-images.githubusercontent.com/22932951/78360687-7627b480-75b7-11ea-9afe-25285042b36d.png)

Die Status der Rücksendung Seite:
![Status](https://user-images.githubusercontent.com/22932951/78360748-8d66a200-75b7-11ea-89e8-ba4eab1f27da.png)

Und das HTML dazu:
![Status HTML](https://user-images.githubusercontent.com/22932951/78360767-96577380-75b7-11ea-81cb-916eba29c9cc.png)

**Comment by Michael-Beutling** [comment]
Leider im falschen Branch: [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue5/amazon-orders.lua)

Schau mal bitte ob der Deine Rücksendung findet.

**Comment by bwess** [comment]
Es gab 32 neue Einträge.

Auf den ersten Blick ist es etwas unübersichtlich, die Rücksendung sieht gut aus, aber für den nicht zurückgesendeten Teil gibt es keinen Eintrag, dafür gibt es alte Einträge noch.

Hier z.B. ein neuer Eintrag (oben), der anscheinend falsch erkannt wurde (Ich habe den Drucker mit Rabatt gekauft, keine Rückgabe):

![Anycubic](https://user-images.githubusercontent.com/22932951/78544467-782d8580-77fa-11ea-8e6c-d2a485c5cfd9.png)

Ich wundere mich, warum der Saldo 0 ist, das kann rechnerisch nicht sein.

**Comment by Michael-Beutling** [comment]
> Es gab 32 neue Einträge.
> 
> Auf den ersten Blick ist es etwas unübersichtlich, die Rücksendung sieht gut aus, aber für den nicht zurückgesendeten Teil gibt es keinen Eintrag, dafür gibt es alte Einträge noch.

Möchtest Du auch für jede nicht zurückgeschickte Position einen Umsatzeintrag? Dann wird es wirklich unübersichtlich :)

> Ich wundere mich, warum der Saldo 0 ist, das kann rechnerisch nicht sein.

Lösch mal bitte die Einträge zu dieser Bestellung in MoneyMoney und aktualisiere das Konto. Könnte sein, dass da ein Zombie-Eintrag drin ist.

**Comment by bwess** [comment]
> Möchtest Du auch für jede nicht zurückgeschickte Position einen Umsatzeintrag? Dann wird es wirklich unübersichtlich :)

Nein, aber ich weiß jetzt was Du meinst. Für mich sind das zwei zufällige Artikel, die nur gemeinsam haben, dass Amazon das als nur eine Bestellung ansieht. Perfekt wäre ein Kauf+Konter für den einen und eine Erstattung+Konter für den anderen, was das Plugin jetzt draus macht ist folgendes, ich verstehe auch warum:

![Beispiel](https://user-images.githubusercontent.com/22932951/78594432-94581380-7848-11ea-83a1-193c2c8e0d6d.png)


> Lösch mal bitte die Einträge zu dieser Bestellung in MoneyMoney und aktualisiere das Konto. Könnte sein, dass da ein Zombie-Eintrag drin ist.

Nach dem Löschen und aktualisieren sieht die 0 schon stimmig aus, bei dem Beispiel mit dem 3D Drucker erscheint jetzt nur noch der Endpreis und eine Konterbuchung dazu, dass es einen massiven Rabatt dafür gab ist jetzt nicht mehr zu sehen. Ist nicht schlimm, aber ich fand es wie es davor war besser.

**Comment by Michael-Beutling** [comment]
Es gibt eine Beta [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/beta/amazon-orders.lua)

Das Thema Rücksendung und Erstattungen habe ich komplett neu geschrieben. Um den dynamischen Faktor abzufangen liest das Plugin das Amazonpostfach und sucht nach Bestellnummern.
