### ISSUE TITLE
Der Server Ihrer Bank meldet einen internen Fehler. Bitte versuchen Sie es später noch einmal.

### ISSUE THREAD

**Issue by luxio** [Michael-Beutling/Amazon-MoneyMoney#40]
Hallo,

ich bekomme seit einigen Tagen beim Abrufen nach einiger Zeit den Fehler:

`Der Server Ihrer Bank meldet einen internen Fehler. Bitte versuchen Sie es später noch einmal.`

Woran könnte das liegen?

**Comment by Michael-Beutling** [comment]
Hallo,

was sind die letzten Ausgaben im Protokollfenster?

Beim Copy&Paste nach GitHub bitte daran denken, das speziell in den Serverantworten persönliche Daten enthalten sind. Die bitte vorher entfernen, Danke.

Gruß Micha

**Comment by netgitdom** [comment]
Hi,

bei mir auch seit einiger Zeit aufgetreten.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/25263529/189531563-136050dc-bcad-43a2-a1b4-f8e2ae5bce41.png">

Viel zu sehen an Fehler ist für mich leider auch nicht.

Ich nutze 2 Faktor Bei Amazon, habe auch schon mal versucht neu einzurichten aber das Ergebnis war das selbe.

MoneyMoney Version 2.4.17
Amazon MoneyMoney Version 1.18

Gruß

**Comment by Michael-Beutling** [comment]
Mal bitte unter den Einstellungen für das Amazon Konto in den Notizen das Attribut **limitOrders** auf der Wert 3 setzten. Damit werden immer nur drei Bestellung abgeholt. 

Ist die Bestellung wo der interne Fehler auftritt im Webbrowser abrufbar? Ist das was spezielles (Software etc) oder nur eine normal gelaufende Krimskrams-Bestellung? 

Gruß Micha

**Comment by netgitdom** [comment]
Oh interessant. Auf den Gedanken bin ich noch gar net gekommen.
Das ist eine Bestellung aus dem Jahr 2000 die auch im Browser eine Fehlermeldung anzeigt.

<img width="928" alt="image" src="https://user-images.githubusercontent.com/25263529/189538060-93ff9ae1-5686-4d74-b3a0-02322a31d2d4.png">

Kann ich die irgendwo ignorieren oder skippen ?

**Comment by luxio** [comment]
Bei mir ist es übrigens auch eine Bestellung aus dem Jahr 2000, bei der beim Aufruf bei Amazon im Browser der Fehler 

`Bei der Anzeige der Details für diese Bestellung ist jetzt ein Fehler aufgetreten. Klicken Sie auf "Bestellungsdetails anzeigen" oder aktualisieren Sie diese Seite.`


erscheint.

**Comment by Michael-Beutling** [comment]
Hallo,

im Master ist eine Version mit dem Feature Blacklist. Über das Attribut **blackListOrders** können Bestellungen ausgelassen werden. Einfach die Bestellnummern mit Kommas getrennt als Wert eingeben.

Die signierte Version folgt noch.

Gruß Micha

**Comment by netgitdom** [comment]
Hi,

das klingt sehr gut. Dann warte ich auf die signierte Version da ich keine Beta am laufen habe von MoneyMoney.
Schon mal vielen vielen Dank für den schnellen Fix :-) 

Gruß

**Comment by luxio** [comment]
@Michael-Beutling Vielen Dank für den schnellen Fix. Der Abgleich läuft bei mir jetzt wieder problemlos.

**Comment by Michael-Beutling** [comment]
Die signierte Version ist da und liegt unter https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/release/amazon-orders.lua bzw. auf der MoneyMoney Homepage https://moneymoney-app.com/extensions/

Gruß Micha

**Comment by luxio** [comment]
Super. Danke. Funktioniert.

**Comment by netgitdom** [comment]
Hier auch, vielen Dank für den schnellen Fix und auch generell für das Plugin :)

**Comment by Michael-Beutling** [comment]
Danke für die Rückmeldungen.
