### ISSUE TITLE
ajaxToken nil - Not fetching messages

### ISSUE THREAD

**Issue by kyrios** [Michael-Beutling/Amazon-MoneyMoney#42]
Account refresh works until the point where messages are received. I did a little digging around. Did amazon change the messages pages? Not only does the /gp/message/ajax/message-list.html? not exist anymore. Also the ajaxToken is not there anymore.

Here is my workaround (for now). Seems to at least get the orders.

    function getMessageList(since)
        return {}
    end

**Comment by Michael-Beutling** [comment]
I'm working at a fix, see #41.
And yes You are right, Amazon has change same details at the message center.

**Comment by Michael-Beutling** [comment]
new signed version which fix the issue: https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/release/amazon-orders.lua
