### ISSUE TITLE
Neue Bestellungen werden nicht verarbeitet

### ISSUE THREAD

**Issue by widike** [Michael-Beutling/Amazon-MoneyMoney#45]
Hi Micha,

jetzt taucht das nächste Problem auf: Die weiteren Bestellungen werden leider nicht verarbeitet wegen invalidPrice?

``` 
12:36:32  1> Received: <!doctype html>
          1> 303-6338120-0932359 string='getOrderInfosFromSummaryHeader invalidPrice'
          1> 303-4959429-1199519 string='getOrderInfosFromSummaryHeader invalidPrice'
          1> 303-0946043-9489911 string='getOrderInfosFromSummaryHeader invalidPrice'
          1> 028-1167744-3723541 string='getOrderInfosFromSummaryHeader invalidPrice'
          1> 028-5747773-8210768 string='getOrderInfosFromSummaryHeader invalidPrice'
          1> 303-3006567-2173107 string='getOrderInfosFromSummaryHeader invalidPrice'
          1> 028-1640885-2473113 string='getOrderInfosFromSummaryHeader invalidPrice'

**Comment by Michael-Beutling** [comment]
Das Script hat in der Bestellübersicht keinen Preis gefunden:
<img width="808" alt="Bildschirmfoto 2022-12-21 um 12 58 00" src="https://user-images.githubusercontent.com/2708948/208900467-e76d251e-c71a-4585-884c-f1f7cbe62510.png">

Das Problem ist das Euro-Symbol, vorher stand da "EUR ".

Attribut regexPrice="€(%d+),(%d%d)" sollte helfen.

Ich habe es im Script korrigiert und teste es gerade.

**Comment by Michael-Beutling** [comment]
Danke für den Hinweis mit dem Tausender-Punkt. Leider ist die RegEx von Lua etwas sparsam und Währungen behandelt das Script auch nicht. Gibt es bei amazon.de denn Buchungen mit Fremdwährungen?

**Comment by Michael-Beutling** [comment]
Danke für den Hinweis, da war noch was vom Debuggen drin.
