### ISSUE TITLE
Keine Postenanzeige nach Restore aus Time Machine

### ISSUE THREAD

**Issue by Annowob** [Michael-Beutling/Amazon-MoneyMoney#47]
Servus,
und vielen dank für die äußerst hilfreiche Extension.
Meine Konstellation:
Ich habe meinen Mac neu aufgesetzt, läuft jetzt unter Ventura 13.1. Aus der Time Machine habe ich die MM DB zurückgeholt. MM (V2.4.19) verwendet diese auch bis auf die Amazon-Extension ohne Probleme - alle Umsätze und Einstellungen vorhanden, Konten, Kreditkarten und PayPal synchronisieren sich problemlos nur Amazon (V1.20) nicht: in der Status-Leiste werden die üblichen "aktualisieren" Meldungen ausgegeben ("Lade..." und "Get Overview", "Get Orders"), aber es kommen keine Buchungen an (und keine Fehlermeldung), es wurden nur die bereits vorhandenen Buchungen angezeigt. 
Ich habe das Amazon-Konto gelöscht und neu hinzugefügt, gleiches Ergebnis (es dauert allerdings länger, weil er durch die Jahre zurück geht). Statt der alten Buchungen steht jetzt "Von Ihrer Bank wurden noch keine Umsätze zur Verfügung gestellt.".
Was kann ich für die Fehleranalyse weiter machen?
Danke vorab :-)

**Comment by Michael-Beutling** [comment]
Hallo,

das hängt vermutlich mit https://github.com/Michael-Beutling/Amazon-MoneyMoney/issues/45 zusammen.

**Comment by Annowob** [comment]
Danke - ich hab die MM-Version aus dem App-Store (=keine Beta Version möglich) - wenn ich das richtig sehe, muss ich dann warten, bis ich über die MoneyMoney Seite eine neue/ signierte Version laden kann?

**Comment by Michael-Beutling** [comment]
Nicht umbedingt, setzt bitte das Attribut "regexPrice" auf "€(%d+),(%d%d)", siehe Screenshot:
![](https://github.com/Michael-Beutling/Amazon-MoneyMoney/blob/master/moneymoney_settings.png)

Einen Neueinlesen aller Bestellungen kann man ggf. mit den Attribut "resetCache" erzwingen. Immer wenn der Wert sich geändert hat, werden alle Bestellungen neu eingelesen.

**Comment by Michael-Beutling** [comment]
Eigentlich sollte dieser Screenshot kommen: https://github.com/Michael-Beutling/Amazon-MoneyMoney/blob/master/moneymoney_settings.png

**Comment by Annowob** [comment]
Danke, ich habe die Attribute (resetCache und regexPrice) hinzugefügt und schon ging es. Vielen Dank & viele Grüße.
