### ISSUE TITLE
Fehlende Bestellungen

### ISSUE THREAD

**Issue by Michael-Beutling** [Michael-Beutling/Amazon-MoneyMoney#5]
> Versuche mal bitte [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue2/amazon-orders.lua)
> 
> Das sollte die alten Bestellung wo keine Details abrufbar sind entsprechend behandeln.

Die drei Bestellungen von 1999 erscheinen jetzt zusammen mit der von 2000, erst als Warnung, danach als Fehler. Soweit so gut. Leider stehen sie ganz oben mit dem heutigen Datum:

![Error](https://user-images.githubusercontent.com/22932951/78077022-e06a0a80-73a7-11ea-9d68-e2bbe8fd475a.png)

Auf Amazon ist das Datum der Bestellungen sichtbar.
Das Datum der restlichen Bestellungen stimmt.

Es wurden 74 neue Umsätze gefunden, die bisher trotz vielfachen Abfragen nicht gefunden wurden. Aus dem Webinterface zusammengerechnet müssten es 466 Bestellungen sein, das Stichwort "Amazon contra" kommt 456 Mal vor, mit den 4 Fehlern fehlen noch 6 Bestellungen. Was könnte ich tun, um herauszufinden, an was das liegen könnte?

_Originally posted by @bwess in https://github.com/Michael-Beutling/Amazon-MoneyMoney/issues/2#issuecomment-606905739_

**Comment by Michael-Beutling** [comment]
ich habe eine Version erstellt die bei der Suche nach den Bestellungen helfen könnte: 

[amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue5/amazon-orders.lua)

am Ende gibt es dann eine Zusammenstellung, mit der man zumindest weiß wo man suchen sollte.

`          1> orderFilterVal=archived  counts= 6 text= 6 archivierte Bestellungen
          1> orderFilterVal=year-2008  counts= 1 text= 1 Bestellung
          1> orderFilterVal=year-2014  counts= 10 text= 10 Bestellungen
          1> orderFilterVal=year-2019  counts= 52 text= 52 Bestellungen
          1> orderFilterVal=year-2009  counts= 3 text= 3 Bestellungen
          1> orderFilterVal=year-2010  counts= 14 text= 14 Bestellungen
          1> orderFilterVal=year-2011  counts= 10 text= 10 Bestellungen
          1> orderFilterVal=year-2012  counts= 6 text= 6 Bestellungen
          1> orderFilterVal=year-2015  counts= 29 text= 29 Bestellungen
          1> orderFilterVal=year-2017  counts= 48 text= 48 Bestellungen
          1> orderFilterVal=year-2013  counts= 11 text= 11 Bestellungen
          1> orderFilterVal=year-2020  counts= 15 text= 15 Bestellungen
          1> orderFilterVal=year-2016  counts= 22 text= 22 Bestellungen
          1> orderFilterVal=year-2018  counts= 19 text= 19 Bestellungen
          1> total= 246
`

**Comment by bwess** [comment]
> ich habe eine Version erstellt die bei der Suche nach den Bestellungen helfen könnte:
> [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue5/amazon-orders.lua)
> am Ende gibt es dann eine Zusammenstellung, mit der man zumindest weiß wo man suchen sollte.

Das ist hilfreich, es fehlt eine aus 2015 und fünf aus 2018, muss ich erst raussuchen...

**Comment by tobsen** [comment]
`1> orderFilterVal=year-2018  counts= 39 text= 40 Bestellungen`

Die eine habe ich gefunden. Hier gibt es keine Buttons rechts.
<img width="940" alt="image" src="https://user-images.githubusercontent.com/132219/78339211-68146c80-7594-11ea-8b87-eef6ce31608a.png">

Ich habe trotzdem noch eine Menge andere im Log stehen, u.a.:

` 1> skip order, get wrong number of elements date='11. Juli 1998' sum='027-9800261-0297756' code='nil'`
`1> skip order, get wrong number of elements date='027-8254477-9720522' sum='nil' code='nil'`
`1> skip order, get wrong number of elements date='11. Juli 1998' sum='027-3642781-0793741' code='nil'`

Das scheinen sind alte ABC-Bücherdienst Bestellungen zu sein. Nummer 2 ist sieht so aus:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/132219/78339862-74e59000-7595-11ea-9ef9-46bb59659523.png">

Wenn du HTML dazu brauchst, kann ich dir gerne helfen.

**Comment by bwess** [comment]
In meinem Fall sind die 5 fehlenden Einträge aus 2018 offenbar 5 digitale Bücher, die ich kostenlos in der Kindle-Edition geschenkt bekommen habe. Der aus 2015 ist eine zu der Zeit kostenlose App im Amazon Store auf Android. Dass die nicht auftauchen finde ich nicht schlimm.

**Comment by Michael-Beutling** [comment]
> `1> orderFilterVal=year-2018 counts= 39 text= 40 Bestellungen`
> 
> Die eine habe ich gefunden. Hier gibt es keine Buttons rechts.

> <img alt="image" width="940" src="https://user-images.githubusercontent.com/132219/78339211-68146c80-7594-11ea-8b87-eef6ce31608a.png">
Den Button braucht es nicht  zwingend, im Kopf fehlt die Summe damit springt er in die Bestelldetails.
Die Links für die Details werden per `xpath('//a[contains(@href,"order-details") and @class="a-link-normal"]')` gesucht. Wenn allerdings die Bestelldetails auch kaputt sind dann ist Ende.
Mit `$x('//a[contains(@href,"order-details") and @class="a-link-normal"]')` kann man in der Entwicklerkonsole des Browsers prüfen ob die Bestelldetails-Links gefunden werden.

> 
> Ich habe trotzdem noch eine Menge andere im Log stehen, u.a.:
> 
> ` 1> skip order, get wrong number of elements date='11. Juli 1998' sum='027-9800261-0297756' code='nil'`
> `1> skip order, get wrong number of elements date='027-8254477-9720522' sum='nil' code='nil'`
> `1> skip order, get wrong number of elements date='11. Juli 1998' sum='027-3642781-0793741' code='nil'`
> 
> Das scheinen sind alte ABC-Bücherdienst Bestellungen zu sein. Nummer 2 ist sieht so aus:
> 
> <img alt="image" width="946" src="https://user-images.githubusercontent.com/132219/78339862-74e59000-7595-11ea-9ef9-46bb59659523.png">
> 
> `1> orderFilterVal=year-1998 counts= 8 text= 8 Bestellungen`
> 
> Wenn du HTML dazu brauchst, kann ich dir gerne helfen.

Gibt es unter Bestelldetails noch was zum Auswerten?

**Comment by Michael-Beutling** [comment]
> In meinem Fall sind die 5 fehlenden Einträge aus 2018 offenbar 5 digitale Bücher, die ich kostenlos in der Kindle-Edition geschenkt bekommen habe. Der aus 2015 ist eine zu der Zeit kostenlose App im Amazon Store auf Android. Dass die nicht auftauchen finde ich nicht schlimm.

Scheinbar gehen digitale Einkäufe nicht, hattest Du auch mal was gekauft und ist das in der Historie? Das PS+ von oben fällt nämlich auch durch die Roste.

**Comment by bwess** [comment]
> Scheinbar gehen digitale Einkäufe nicht, hattest Du auch mal was gekauft und ist das in der Historie? Das PS+ von oben fällt nämlich auch durch die Roste.

Bücher lese ich ganz altmodisch immer noch auf totem Holz, meine Software/Spiele/Steam Codes kamen alle noch in einer Schachtel oder nicht von Amazon, Apps und Abos sind auch keine dabei, ich finde tatsächlich nichts...

**Comment by Michael-Beutling** [comment]
Neue Version [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue5/amazon-orders.lua), kommt zumindest mit App Käufen klar. Vielleicht fängt es noch die eine oder andere Bestellung.

**Comment by tobsen** [comment]
<img width="987" alt="image" src="https://user-images.githubusercontent.com/132219/78505524-4d98e980-7774-11ea-8152-f741d54d1e1b.png">

Ich habe die neue Version noch nicht ausprobiert, sollte man eigentlich das Konto neu hinzufügen oder einfach nur das Script aktualisieren?

**Comment by Michael-Beutling** [comment]
Script aktualisieren sollte reichen, am besten das Script [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue5/amazon-orders.lua) frisch ziehen, sind noch ein paar Änderungen drin für Rücksendung.

**Comment by bwess** [comment]
> Neue Version [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue5/amazon-orders.lua), kommt zumindest mit App Käufen klar. Vielleicht fängt es noch die eine oder andere Bestellung.

Bei mir funktioniert das für alle 6 fehlenden Artikel (Bücher und App), gut zu finden am Stichwort D01.

**Comment by Michael-Beutling** [comment]
Es gibt eine Beta [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/beta/amazon-orders.lua)
