### ISSUE TITLE
Neue Bestellungen tauchen nicht mehr auf

### ISSUE THREAD

**Issue by jonathanlang** [Michael-Beutling/Amazon-MoneyMoney#50]
Scheinbar klappt das Parsing nicht mehr so richtig. Neue Bestellungen werden mir nicht mehr angezeigt. Hab grad die aktuellste Version von der MoneyMoney Seite geladen, aber meine Bestellungen von Januar fehlen. 
Kann ich helfen das zu diagnostizieren? 
Danke!

**Comment by Michael-Beutling** [comment]
Hallo Jonathan,

kommen Fehlermeldungen oder läuft das Script durch? 
Aktuell läuft das Script bei mir durch und erkennt alle Bestellungen.

Gruß Micha

**Comment by jonathanlang** [comment]
Merkwürdig, heute wurden die Bestellungen wieder erfolgreich geladen. Vielleicht ein temporäres Problem... danke trotzdem!

**Comment by augenring** [comment]
Hallo, 
leider hier auch so, dass nach dem 25.1. nichts mehr durchkommt.
Keine Fehlermeldungen, Script läuft durch. Testet Amazon mal wieder irgendetwas..?
Viele Grüße

**Comment by augenring** [comment]
Meca Culpa. Ich habe nochmal das Plugin neu installiert und nun läuft es wieder.
Vielleicht habe ich vorher nicht richtig auf die letzte Version angepasst o.ä.

Sorry und vielen Dank für die tolle Arbeit

**Comment by Michael-Beutling** [comment]
Okay, kein Problem.

**Comment by rhuss** [comment]
Ich habe seit exakt 25.1 das exak gleich Problem, dass neue Bestellung nicht mehr aktualisiert werden. Denke ich werde das Plugin auch nochmal neu installierten. Evtl ein Problem mit dem Cache ?

**Comment by Michael-Beutling** [comment]
Ein zurücksetzen des Caches kann man erzwingen, durch setzen des Attributs 'resetCache', immer wenn man den Wert ändert, wird der Cache verworfen und alles neu eingelesen:
<img width="313" alt="Bildschirmfoto 2023-02-06 um 11 57 14" src="https://user-images.githubusercontent.com/2708948/216954406-8d450ae0-1dd9-465b-941e-bb96e9a461bc.png">
<img width="442" alt="Bildschirmfoto 2023-02-06 um 11 57 54" src="https://user-images.githubusercontent.com/2708948/216954496-932b544c-ee21-48ed-bea0-8ea4d2e45cc9.png">

**Comment by AlexanderWillner** [comment]
Weiß nicht, ob das Ticket hier geschlossen sein sollte: ich habe die selbe Beobachtung seit Februar. Das setzen des Attributs `resetCache` hat nur den Kontostand auf `0` gesetzt. Durch Überschreiben des Plugins mit der selben Version im Ordner `Extensions` konnte ich die Synchronisation wieder reparieren. 

Auffällig war hier auch, dass es keine Fehlermeldungen gab. Das Skript lief laut Log soweit durch, hat aber augenscheinlich nichts gemacht. Das macht die Fehlersuche natürlich nicht einfacher...leider habe ich den Log nicht mehr, aber grob passierte folgendes (lief ca. 20 Sekunden):
> login success
> name=xxx
> Getting balance and transactions for Amazon...
> Getting transactions since 01.02.2024...
> ...
> Get order overview for "den letzten 30 Tagen"
> ...
> ajaxToken nil
