### ISSUE TITLE
amazon-Konto aktualisiert sich nicht mehr korrekt

### ISSUE THREAD

**Issue by Seeberg41** [Michael-Beutling/Amazon-MoneyMoney#60]
Guten Tag Herr Beutling, seit einigen Tagen kann ich mit "MoneyMoney" und Ihrem amzon-PlugIn mein Konto bei amazon nicht mehr aktualisieren. Die neuesten Einkäufe werden nicht abgerufen. Ein Workaround ist im Moment die komplette Entfernung des Kontos und eine Neuanlage. Dann klappt die Aktualisierung auch mit den neuesten Einkäufen. Das ist natürlich sehr mühsam und dauert auch ziemlich lange. ich habe Ihnen die lua-Datei mitgeschickt, die bei mir im Einsatz ist (musste sie umbenennen, einfach das ".txt" löschen). 
[amazon-orders.lua.txt](https://github.com/Michael-Beutling/Amazon-MoneyMoney/files/13457936/amazon-orders.lua.txt)
Könnten Sie mal schauen, was da krumm ist? Bisher lief das Abholen neuer Umsätze ja vollkommen problemlos. Dankeschön!
Mit freundlichem Gruß
W. Schneider

**Comment by ronau** [comment]
Bei mir das gleiche Verhalten. Keine Fehlermeldung, aber es werden einfach keine neuen Transaktionen mehr abgerufen.

Was geholfen hat: Mit Rechtsklick aufs Konto > "Zugangsdaten bearbeiten ...". Dann Zugangsdaten bestätigen, ggf. nochmal den OTP Code eingeben und dann ruft er alle Transaktionen erneut ab. Die neuesten sind jetzt aber auch mit dabei.

Immerhin brauchte ich das Konto nicht entfernen, das hätte meine Kategorisierungen von vielen Jahren zerstört. 🙈


Falls Bedarf besteht, könnte ich ein Logfile hochladen.

**Comment by Seeberg41** [comment]
Frage 1: Ist mit "Zugangsdaten bestätigen" gemeint auf "Abbrechen" oder auf "Weiter" zu klicken?
Frage 2: Ist mit "ggf. nochmal den OTP Code eingeben" gemeint, das Passwort für amazon erneut einzugeben und danach auf "Weiter" zu klicken?

**Comment by ronau** [comment]
Zu Frage 1: Die Zugangsdaten sollten vorausgefüllt sein. Ich habe dann auf "Weiter" geklickt.
![image](https://github.com/Michael-Beutling/Amazon-MoneyMoney/assets/5237327/9a8f0303-15ea-4f10-8097-5129b3e22d49)

Zu Frage 2: Im nächsten Schritt musste ich den OTP Code erneut eingeben. Das ist die 2-Faktor-Authentifizierung für den Login bei Amazon. Soweit ich weiß ist das nicht verpflichtend, ich habe es aus Sicherheitsgründen allerdings eingerichtet.
Nachdem ich den 6-stelligen OTP Code aus meiner 2-Faktor-App eingegeben habe, habe ich noch einmal auf "Weiter" geklickt.

Anscheinend hat dies eine "Neuanmeldung" beim Amazon-Konto bewirkt. Kann natürlich sein, dass das ohne eingerichtete 2-Faktor-Authentifizierung nicht funktioniert.
Alternativ könntest du an der Stelle mal absichtlich ein falsches Passwort eingeben. Der Login sollte fehlschlagen, vermutlich darfst du dann nochmal neu dein Passwort eingeben, diesmal richtig. Eventuell bewirkt das eine "Neuanmeldung".

Im nächsten Schritt konnte ich die Konten an-/abwählen, auf "Weiter" klicken und er hat angefangen, die Transaktionen zu laden.

**Comment by Seeberg41** [comment]
Ich habe nur die 1-Faktor-Authentifizierung bei amazon eingerichtet. Ich muss erstmal wieder was bestellen, um die Abfrage zu überprüfen. Aber falls das nicht korrekt klappen sollte, werde ich mal den Tipp mit dem bewusst "falschen" Passwort probieren. Mal schauen, was dann passiert. Ich werde dann berichten. Aber danke für die Tipps!

**Comment by Seeberg41** [comment]
So, ich habe gerade etwas bei amazon gekauft und der Kauf wird mir plötzlich wieder in MoneyMoney angezeigt. Ich hoffe, dass das so bleibt!

**Comment by jandamm** [comment]
Ich habe so ein ähnliches Problem, wenn eine Amazon Bestellung (Warenkorb) in mehrere Bestellungen (Bestellnummern) aufgeteilt wird.
Dann wird bei mir nur die erste Bestellung geladen und alle weiteren werden ignoriert.

**Comment by jandamm** [comment]
Bei mir hilft es scheinbar auch nicht, dass ich 2FA deaktiviere.

**Comment by ronau** [comment]
Ich habe heute auch mal wieder das Problem, dass er einfach nicht die neuesten Transaktionen lädt.
Kennwort aus MoneyMoney löschen oder OTP bei Amazon zurücksetzen hat alles nicht geholfen. MoneyMoney fragt zwar nach allem neu nach (Amazon-Kennwort bzw. OTP), aber die neuesten Transaktionen werden dennoch nicht geladen.

**Comment by Seeberg41** [comment]
Es gibt einen Workaround, der allerdings etwas dauert: Ich ändere in MoneyMoney (MM) das amazon-Passwort und wähle mich ein. Das führt (natürlich) zu einem Fehler. Dann gebe ich das richtige Passwort ein und MM zeigt mir die Konten an. Ich wähle die oberste Option und MM legt los. Es geht bei mir zurück bis ins Jahr 2006 und maximal werden 250 Käufe abgerufen. Das muss ich dann so lange machen, bis MM alles abgeholt hat (dauert ca. 15-20 Minuten). Komischerweise sind dann auch die neuesten Käufe mit dabei. Nach ein paar Käufen klappt es aber wieder nicht mit allen Käufen und ich fange wieder von vorne an :-((

**Comment by jandamm** [comment]
@Seeberg41, etwas leichter aber nicht schneller geht es, wenn man den Wert `resetCache` in de Kontodetails setzt (siehe Readme).
Damit werden dann auch die neuen Transaktionen geladen, aber leider muss man die kompletten Buchung erneut laden.
Ich habe mir abgewöhnt, dass ich vorher alle Transaktionen als erledigt markiere, sodass doppelte Buchungen in der Historie leichter gefunden werden können.

**Comment by ronau** [comment]
@Seeberg41 Ja, das hatte ich oben im zweiten Post auch schon geschrieben, dass man notfalls alles neu laden kann.

@jandamm @Seeberg41 Danke für den Tipp, das ist praktisch. Aber so oder so ist das Neuladen aller Transaktionen ein ziemlich mühsamer Workaround. Weiß ich nicht, ob ich das jetzt ständig so machen möchte.

Weiß nicht, ob der @Michael-Beutling was dazu sagen kann. Ist bestimmt auch immer in irrer Aufwand, das Scrapen der Seite anzupassen, nur weil Amazon mal wieder irgendeine Kleinigkeit geändert hat.

**Comment by darkmattercoder** [comment]
Bei mir ist das plugin inzwischen auch mehr oder weniger unbrauchbar geworden. Der Workaround mit dem Passwort reset funktioniert, aber das einlesen dauert dann halt Stundenlang bei vielen Umsätzen. Ich verstehe noch nicht so ganz, warum bspw. brandaktuelle Buchungen auftauchen, aber Käufe von vor zwei Wochen bspw. nicht.

**Comment by jandamm** [comment]
Mein Gefühl ist, dass Amazon gerade einiges an A/B-Tests fährt.
Bei mir ist es ein täglicher Wechsel ob ich ein Passwort eingeben muss oder nicht.

**Comment by Seeberg41** [comment]
Nun lief das Plugin einige Zeit einigermaßen fehlerfrei. Leider gibt es jetzt schon wieder Probleme, die ich selber nicht mehr lösen kann: 

Ein Kauf von gestern wird von MM nicht abgeholt. Also habe ich wieder ein falsches Passwort eingegeben und die Captcha-Abfrage forciert. In StarMoney das Captcha ausgefüllt und trotzdem klappte die Abfrage nicht mehr.

Dann habe ich das komplette amazon-Konto gelöscht und ein neues angelegt. Und nun werden nur noch 66 Käufe angezeigt (rückwirkend bis 2001!!). Auch nach einer weiteren Löschung das gleiche Ergebnis:  Statt über 3800 Käufe nur noch 66!

So macht das echt keinen Spaß und ist völlig unbrauchbar.

Schade.

**Comment by jsadbjsadljnsa** [comment]
Bei meiner Frau ebenso. Lediglich acht Umsätze aus dem Jahr 2008 tauchen auf. Mehr nicht. 

Bei mir passt es mit den knapp 700 Bestellungen. 

Leider unbrauchbar. Aber leider meldet sich auch @Michael-Beutling nicht mehr. Ich habe auch leider selber keine Ahnung, wie man das Plugin weiter programmieren kann.
