### ISSUE TITLE
Ebenfalls Probleme mit alten Bestellungen

### ISSUE THREAD

**Issue by Stopuhr** [Michael-Beutling/Amazon-MoneyMoney#7]
Moin!
Vorweg danke für die Erweiterung.
Eigentlich bin ich hauptsächlich an neuen Bestellungen interessiert, damit das Wegsortieren der Buchungen leichter fällt. Dennoch melde ich jetzt mein Probleme und bewusst in einem eigenen Thread, weil ich die Ursache nicht so gut einschätzen kann.

Im Einsatz habe ich den heutigen Master.
Error: Invalid order found, a account reload can be fix it.

Meine Bestellungen gehen bis 1999 zurück. So wie es für mich aussieht, geht bis 2002 alles gut. Im Dezember wurde 2 Bücher bestellt, die verbucht wurden.
Zwei DVDs aus dem Januar tauchen allerdings gar nicht auf - es sind die ersten Artikel ohne Button und weitere Details.
Als Fehlerhaft wird in MoneyMoney allerdings die letzte (oben stehende) Bestellung angezeigt. Die zweite Bestellung aus 2001 und die beiden aus 2000 und 1999 fehlen ganz - was auch nicht wundert.
Übrigens habe ich im Protokoll gesehen, dass die Jahre aber alle abgefragt wurden.

---

Jetzt habe ich noch eine Verständnisfrage:
Sehe ich es richtig, dass per Default alle drei Konten für sich abgerufen werden? Kann ich dann das Parsen zukünftig beschleunigen, wenn ich z.B. nur das Mix-Konto nutze?

und eine zweite:
Wenn einmal alle korrekt geladen werden, dann geht das Script nicht wieder alle  Bestellungen durch, oder? Bei meinen Versuchen wurde immer wieder alle geladen, selbst die Jahrgänge, die schon erfolgreich geparst wurden.

---

btw: Die Fehlermeldung könnte zum einen genauer sein, ich habe gesehen, dass die Ursache an verschiedenen Stellen auftreten kann, zum anderen passt die Grammatik auch nicht so ganz: 'can be helpfull' oder 'may fix it' ;-).

**Comment by Michael-Beutling** [comment]
Im Moment ist der Master bezüglich alter Bestellung kaputt, siehe issue 5.


> Sehe ich es richtig, dass per Default alle drei Konten für sich abgerufen werden? Kann ich dann das Parsen zukünftig beschleunigen, wenn ich z.B. nur das Mix-Konto nutze?

Die drei Konten teilen sich den Cache, aber rufen einzel die Übersicht der letzten sechs Monate ab. Da kann man aber noch was optimieren.
 
> Wenn einmal alle korrekt geladen werden, dann geht das Script nicht wieder alle Bestellungen durch, oder? Bei meinen Versuchen wurde immer wieder alle geladen, selbst die Jahrgänge, die schon erfolgreich geparst wurden.

Vermutlich hängt das mit alten Bestellungen zusammen, nur wenn alles erfolgreich gecachet wurde wird der Jahrgang zukünftig ausgelassen.

> 
> btw: Die Fehlermeldung könnte zum einen genauer sein, ich habe gesehen, dass die Ursache an verschiedenen Stellen auftreten kann, zum anderen passt die Grammatik auch nicht so ganz: 'can be helpfull' oder 'may fix it' ;-).

Das Verhalten wurde im Rahmen des Issue schon verändert. Der Text ist allerdings noch... "may fix it" klingt aber runder...

**Comment by Michael-Beutling** [comment]
Es gibt eine Beta [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/beta/amazon-orders.lua)

Da das Einlesen der Bestellung neu geschrieben wurde, hoffe ich das alte Bestellungen jetzt besser ausgelesen werden. Schreibt mal ob es besser klappt.

**Comment by Stopuhr** [comment]
Moin, sry für die späte Antwort.
Ich habe einmal die Konten gelöscht, das Plugin geladen und neu abfragen lassen.
Leider ist alles beim alten. Das Problem besteht noch.
Gib bescheid, wenn und wie ich ggf. helfen kann. Vielleicht wäre bei diesen 'alte Bestellungen' gut, wenn man testweise die Bestellungen vom letzten Jahr an Parsen könnte. Dann ist das Log auch nicht so voll, bei mir bremst das dann alles aus, so dass eine Analyse auch schwer fällt.

**Comment by Stopuhr** [comment]
Alles fein!
Hab noch einmal den neuesten Stand geladen, damit sieht jetzt alles gut aus. Bin damit auch wieder auf dem normalen Release-Pfad.
Danke für den Einsatz!!
