### ISSUE TITLE
Ignoring 'amazon-orders.lua' because signature verification failed.

### ISSUE THREAD

**Issue by MacGyverBeta** [Michael-Beutling/Amazon-MoneyMoney#8]
Hello guys,

I did install the extension like described (and have already installed another extension successfully there) but when starting Money Money with the amazon-orders.lua Extension installed, I get the following error:
21:13:37  Ignoring 'amazon-orders.lua' because signature verification failed.

I did also install your lates version from issue #3 - [here](https://github.com/Michael-Beutling/Amazon-MoneyMoney/issues/3#issuecomment-609464201)

It did not help.
Everything else works fine...

I hope you can help me.
Thank you.

**Comment by Michael-Beutling** [comment]
You need the beta version from MoneyMoney by check "betas" in the settings and force an update. After the update you must disable the signature check in the extension tab in the settings.

Be aware, make a backup!

**Comment by MacGyverBeta** [comment]
This did work! Thank you!

**Comment by widomattern** [comment]
Thanks a lot, the extension helps me a lot. I would also like to spend some money in the coffee box. Unfortunately I have the same problem with my Amazon Business Account.
Is there a possibility for the Mac App Store version of MoneyMoney to use the version from case #3, or will there be a compatible version at a later time.
