### ISSUE TITLE
amazon-orders.lua:462: attempt to index upvalue 'html' (a nil value)

### ISSUE THREAD

**Issue by Leololololo** [Michael-Beutling/Amazon-MoneyMoney#9]
Echt tolles Plugin! Ersteinmal Danke! Leider läuft es bei mir irgendwie nicht. Neuste MoneyMoney Beta ist am start.

Anlegen des Kontos ist kein Problem nur nach dem ersten refresh kommt folgende Fehlermeldung und es wird kein "kauf" abgerufen.

amazon-orders.lua:462: attempt to index upvalue 'html' (a nil value)

Ich habe einen deutschen Amazon Business Account.

**Comment by Michael-Beutling** [comment]
Welche Version vom Script (commit) hast Du am Start?

**Comment by Leololololo** [comment]
Neuste Version von der Github Seite. Heute mal mit einem anderen Mac ausprobiert und kriege gleich beim Setup folgende ähnliche Meldung:

      Lade Kontostand und Umsätze für Amazon Unkown ...
          Getting transactions since 12.04.2019...
          Refresh inverse
          amazon-orders.lua:233: bad argument #1 to 'request' (string expected, got nil)

Schau mal.

**Comment by Michael-Beutling** [comment]
Es gibt eine Beta [amazon-orders.lua](https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/beta/amazon-orders.lua)

**Comment by Leololololo** [comment]
Cool danke, wollte sie gleich ausprobieren. Wenn ich das .txt wegnehme und sie in den Extension Ordner schmeisse taucht leider nichts in meinem Moneymoney auf. Auch nach mehrmaligem Moneymoney neustart nicht :(

**Comment by Michael-Beutling** [comment]
Hast eine Beta-Version von MoneyMoney und die Signaturprüfung von MoneyMoney abgeschaltet?

**Comment by Leololololo** [comment]
ja, die anderen extensions tauchen auf.

**Comment by Michael-Beutling** [comment]
Kommen Meldungen  im Log-Fenster?
Im Terminal eingeben:
`ls -l  ~/Library/Containers/com.moneymoney-app.retail/Data/Library/Application\ Support/MoneyMoney/Extensions/`
liefert:
`-rw-r--r--  2 micha  staff  39610 13 Apr 09:31 amazon-orders.lua`

**Comment by Leololololo** [comment]
guter tipp...also bei mir liefert es 

-rw-r--r--@ 1 macleo  staff  39610 13 Apr 11:12 amazon-orders.lua.txt

obwohl ich das txt im finder nicht mehr sehe...wtf...

**Comment by Michael-Beutling** [comment]
Im Finder in den Einstellungen/Erweitert "Alle Dateinamensuffixe einblenden", Haken raus. 
Kategorie "Bescheuerte Standardeinstellungen"

**Comment by Leololololo** [comment]
Oh man! Das stelle ich bei allen immer aus und bei mir selbst vergesse ich es. Danke ...ich schäme mich

Jetzt klappt es beim einbinden. Aber dann abrufen des ersten Umsatz habe ich das hier.

amazon-orders.lua:895: attempt to index upvalue 'html' (a nil value)

**Comment by Michael-Beutling** [comment]
Das könnte Deinen Business Account zusammenhängen.

Bitte diese Version installieren: https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue9/amazon-orders.lua


Dann MoneyMoney schließen und neu starten (um das Log löschen), Amazon Konto einrichten/bzw. neu laden, im Log alles markieren und kopieren, im Terminal `pbpaste |grep "1> line"`eingeben

So sollte es aussehen:
`          1> line 911
          1> line 912
          1> line 915
          1> line 916
          1> line 917
13:37:37  1> line 918
          1> line 919
          1> line 921
          1> line 924
          1> line 925
          1> line 927
          1> line 928
          1> line 929
          1> line 941
          1> line 221
          1> line 224
          1> line 237
          1> line 238
          1> line 243
.......
 1> line 1053
          1> line 1054
          1> line 1064
`

Was kommt bei Dir?

**Comment by Leololololo** [comment]
im terminal erfolgt auf 

> pbpaste |grep "1> line"

leider garnichts. Ich habe dir mal das Log angehängt

![Bildschirmfoto 2020-04-13 um 14 48 33](https://user-images.githubusercontent.com/63395206/79121560-dc6dbd80-7d95-11ea-9652-48d927ce168f.png)
[Log.txt](https://github.com/Michael-Beutling/Amazon-MoneyMoney/files/4469535/Log.txt)

**Comment by Leololololo** [comment]
sorry ich dummerchen.

`MacLeos-iMac-2:~ macleo$ pbpaste |grep "1> line"
          1> line 911
          1> line 912
          1> line 915
          1> line 916
          1> line 917
          1> line 918
          1> line 919
          1> line 921
          1> line 924
          1> line 925
          1> line 927
          1> line 941
          1> line 221
          1> line 224
          1> line 237
          1> line 238
          1> line 243
          1> line 246
          1> line 254
          1> line 255
          1> line 258
          1> line 267
          1> line 258
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 260
          1> line 262
          1> line 259
          1> line 267
          1> line 270
          1> line 271
          1> line 272
          1> line 273
          1> line 302
          1> line 303
          1> line 304
          1> line 328
          1> line 330
          1> line 331
          1> line 333
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 340
          1> line 339
          1> line 344
          1> line 349
          1> line 942
          1> line 221
          1> line 222
          1> line 944
          1> line 893
          1> line 894
          1> line 895`

**Comment by Michael-Beutling** [comment]
Das zuviel hast zumindest den Vorteil das ich gleich das Problem sehen. 
In den Logs ist übrigens immer die komplette Antwort von Amazon, also etwas mehr als man zeigen möchte ;)

**Comment by Michael-Beutling** [comment]
Neue Version: https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue9/amazon-orders.lua

**Comment by Leololololo** [comment]
> Das zuviel hast zumindest den Vorteil das ich gleich das Problem sehen.
> In den Logs ist übrigens immer die komplette Antwort von Amazon, also etwas mehr als man zeigen möchte ;)

Ja das hatte ich mir in dem moment auch gedacht, hatte nur die schnauze voll das du blinde kuh spielen musst. Ändere gleichmal vorsorglich das Kennwort....es ist ja wenigstens noch 2faktor dringewesen. Es sieht bisher gut aus! Ich glaube wir haben es! Er ruft jetzt ab!. VIELEN VIELEN DANK FÜR DIE GEDULD!

**Comment by Leololololo** [comment]
verdammt. Er zeigt mir jetzt nur 5 purchases und das sind wahrscheinlich die früher privat gekaufen dinge da es nur firetv apps sind etc.

Die vielen Business purchases tauchen nicht auf. Any thoughts?

**Comment by Michael-Beutling** [comment]
Das hatte ich schon befürchtet, Amazon hat vermutlich für jede Kundenart eine eigene Darstellung der Bestellungen. Ich schau mal, ob ich da einen praktikablen Lösungsweg finde.

**Comment by Michael-Beutling** [comment]
weiter gehts, ich hoffe ich habe einen Ansatz gefunden und zwar ein Python Script (https://github.com/Michael-Beutling/Amazon-MoneyMoney/blob/issue9/HTMLWasher.py) was eine Webseite anonymisiert aber die Struktur erhält.

Im Safari (Chrome ging bei mir nicht) die Bestellübersicht aufrufen und die Quelltext der Seite kopieren.

mit `pbpaste |python3 HTMLWasher.py ` sollten zwei Dateien erzeugt werden, eine html Datei zum posten und eine txt Datei in der die Sachen drin sind die man nicht posten möchte ;)

ggf. Muss man Python3 per brew und HTMLParser per pip3 nach installieren.
 

Beispiel: 
[public_page.html.zip](https://github.com/Michael-Beutling/Amazon-MoneyMoney/files/4496345/public_page.html.zip)

**Comment by timpritlove** [comment]
Also bei mir ging es mit dem alten Release und dem Business Account auch nicht, die aktuelle Beta arbeitet sich laut Log aber zumindest ohne Fehler beständig durch alle Jahre durch, aber am Ende landen keine Transaktionen in MoneyMoney.

Kann ich irgendwie dazu beitragen, den Bug zu finden?

**Comment by Michael-Beutling** [comment]
@timpritlove Erstmal Danke für die Aufmerksamkeit in der Freakshow. 
Irgendwas ist bei Business Accounts in der Darstellung anders, deswegen hatte ich ja das kleine Pythonscript hochgeladen. Wenn jemand mit einen Business Account mal die Bestellübersicht (eine Seite reicht erstmal) da durch schieben würde und die public hier hochladen würde, hätte ich schon mal die Struktur.  
Danke.

**Comment by widomattern** [comment]
Bei mir verhält es ich genau wie bei timpritlove.
Hier die Struktur von meinem Business Account:
[public_page.html.zip](https://github.com/Michael-Beutling/Amazon-MoneyMoney/files/4496762/public_page.html.zip)

**Comment by Michael-Beutling** [comment]
Danke, im Kopf der Übersicht wurden 4 Element gefunden statt 3.
Bitte https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue9/amazon-orders.lua prüfen ob es klappt. 
Es sollten Meldungen kommen am Ende `unkown element ...`, hier bitte eine Rückmeldung ob das in die Bestellung mit rein soll.

**Comment by widomattern** [comment]
Die Bestellungen wurden mit [https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue9/amazon-orders.lua](url) nun vollständig abgerufen und werden in MoneyMoney auch richtig angezeigt.

Die Meldungen am Ende mit beinhalten den Firmennamen:
`17:28:12  1> Received:
	1> string='unkown element' string='Firma XYZ GmbH & Co. KG'
	...`

In meinem persönlichen Fall ist das Feld nicht weiter von Bedeutung, da ich nur eine Firma in dem Account habe - für Anwender mit mehren Firmen könnte diese Info jedoch von Bedeutung sein.
In der Bestellübersicht von Amazon wird in dem Feld `AUFGEGEBEN VON` auch noch der Name des Benutzer-Accounts (Einkäufer) mit Vor und Zuname ausgegeben, diese Informationen wäre (evtl. auch in Kombination mit dem Firmenname) in Bestellungen evtl. für alle Business-Account-Nutzer relevant.

Unabhängig davon wird beim Anlegen des Business Accounts der Name noch nicht erkannt/übernommen:
`17:26:40  Received:                                                                                                                                                                                                
	Web Banking account: Amazon Unkown (mix)
	Web Banking account: Amazon Unkown (normal)
	Web Banking account: Amazon Unkown (inverse)
	...`
Bei einem privaten Account wird `Amazon <Vorname>` angezeigt.

Auch der Abruf (mix) eines privaten Accounts lief nun vollständig (mit Saldo = 0) und in einem Durchgang über alle (>1.000) Bestellungen.

**Comment by Michael-Beutling** [comment]
@widomattern 
Steht in _T70_ der Benutzername? Der Class Name "abnav-accountfor" deutet auf das Konto hin.
Welche Textmarken sind die Namen die meinst?

**Comment by widomattern** [comment]
_T64_='Lieferung an {Firma XYZ (ohne Rechtsform)}'
_T65_='{PLZ} {Ort}'
_T67_='DE'
_T69_='Hallo, {Vorname Besteller}'
_T70_='Konto für Firma XYZ GmbH & Co. KG'
**_T133_='Firma XYZ GmbH & Co. KG'**
_T134_='Aufgegeben von'
**_T135_='{Vor- und Nachname von Besteller}'**

**Comment by Michael-Beutling** [comment]
Danke für die Zuarbeit. 
Passt es so https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue9/amazon-orders.lua

Wenn ich keinen Dreher drin habe sollte der Mandant (Firma xyz) als Konto und der Besteller als Referenz in MoneyMoney geführt werden.
Hinweis: Die Daten werden erst sichtbar wenn man eine Bestellung ausgewählt hat. Die Suche funkt über beide Felder, aber die automatische Kategoriezuordnung geht leider nur bei dem Referenzfeld.
Bin für etwaige Verbesserungsvorschläge dankbar.

**Comment by widomattern** [comment]
Sehr gerne.
Die Anzeige des Firmennamens beim Anlegen eines Business Accounts funktioniert jetzt:
`09:50:37  Received: 
	Web Banking account: Amazon Firma XYZ GmbH & Co. KG (mix)
	Web Banking account: Amazon Firma XYZ GmbH & Co. KG (normal)
	Web Banking account: Amazon Firma XYZ GmbH & Co. KG (inverse)`

Auch die Übernahme des Firmennamens {Firma XYZ GmbH & Co. KG} in das Feld `Konto` und die Übernahme des {Vor- und Nachname von Besteller} in die `Referenz` funktionieren.

Und auch das Anlegen und der Abruf eines privaten Accounts funktionieren wie bisher.
Evtl. wäre es hier noch hilfreich den Namen (und evtl. die Adresse) aus dem Feld `Versandadresse` in die `Referenz` zu speichern, so wäre bei mehreren Versandadressen auch hier eine einfache Zuordnung möglich.

Für mich löst somit deine MoneyMoney-Erweiterung aktuell ein bisher Zeit-aufwendiges Problem bei der Zuordnung von Lastschriften und Bestellungen von Amazon in meiner Buchhaltung.
Vielen Dank.

**Comment by widomattern** [comment]
Evtl. ist as auch bei privaten Accounts hilfreich den Account {Vor- und Nachname} in das Feld `Konto` zu übernehmen, so dass Menschen mit mehreren privaten Accounts diese besser unterscheiden können.

**Comment by Michael-Beutling** [comment]
@widomattern Meinst es so? https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue9/amazon-orders.lua

**Comment by widomattern** [comment]
Ja, danke.
- Die Übernahme der `Versandadresse` {Name und Adresse} bei privaten Accounts in die `Referenz` funktioniert und finde ich hilfreich - auch weil so danach gesucht werden kann.
- In das Feld `Konto` wird nun der Name des Kontos aus MoneyMoney übernommen, evtl. bietet sich hier eher der `Kontoinhaber` {eMail-Adresse des Amazon-Accounts} aus MoneyMoney an. Das mag aber evtl. auch nur in meinem Fall die bessere Lösung sein, da ich für jeden Online-Account eigene eMail-Adressen verwende.

**Comment by Michael-Beutling** [comment]
Jetzt ist es der Kontoinhaber, hat den Vorteil das der Name des Kontos (Links sichtbar) und des Kontoinhabers, der sonst nicht sichtbar unabhängig, eingestellt werden können.

**Comment by widomattern** [comment]
Danke, funktioniert.

**Comment by Leololololo** [comment]
Ui...soviel passiert hier! Bei mir geht es jetzt auch! Bin Super Glücklich! Danke Michael!

**Comment by timpritlove** [comment]
Für mich funktioniert das leider noch nicht. Bei mir wird nur eine Bestellung korrekt in MoneyMoney importiert. Alle anderen werfen Fehler im Log a la:

`          1> string='unkown elements' string='13. Februar 2019#Tim Pritlove#EUR 14,95#Ersatzteil Kopfhörer#304-5405586-5482757'
`

**Comment by Michael-Beutling** [comment]
Jetzt sollte es klappen, das zusätzliche Feld ("Ersatzteil Kopfhörer") wird als Umsatzart eingetragen und muss mindestens fünf Zeichen lang sein, sonst unterdrückt es MoneyMoney.

https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue9/amazon-orders.lua

**Comment by timpritlove** [comment]
Jetzt kriege ich ein

`          1> amazon-orders.lua:823: table index is nil
`

**Comment by timpritlove** [comment]
Ich kann Dir auch temporär Zugang zu dem Account geben, wenn es weiterhilft.

**Comment by Michael-Beutling** [comment]
@timpritlove Danke für das Vertrauen, aber nicht nötig. Hatte es kaputt optimiert.

Next try:
https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/issue9/amazon-orders.lua

**Comment by timpritlove** [comment]
Jetzt sind die Fehler weg, aber es taucht trotzdem nur eine Transaktion auf. Alle, die bisher Fehler geworfen haben werden nicht übergeben.

**Comment by Michael-Beutling** [comment]
Zahlendreher :(
Jetzt geht es in der Beta weiter:
https://raw.githubusercontent.com/Michael-Beutling/Amazon-MoneyMoney/beta/amazon-orders.lua
